builds:
  - main: ./cmd/wing
    binary: wing
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags: -tags netgo
  - main: ./cmd/tarmak
    binary: tarmak
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags: -tags netgo
  - main: ./cmd/terraform-provider-awstag
    binary: terraform-provider-awstag
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags: -tags netgo
archive:
  format: binary
release:
  github:
    owner: jetstack
    name: tarmak

sign:
  signature: "${artifact}.asc"
  args: ["-u", "tech+releases@jetstack.io", "--armor", "--output", "${signature}", "--detach-sign", "${artifact}"]
