// Copyright Jetstack Ltd. See LICENSE for details.
// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jetstack/tarmak/pkg/wing/client (interfaces: Interface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/jetstack/tarmak/pkg/wing/client/typed/wing/v1alpha1"
	discovery "k8s.io/client-go/discovery"
	reflect "reflect"
)

// MockInterface is a mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Discovery mocks base method
func (m *MockInterface) Discovery() discovery.DiscoveryInterface {
	ret := m.ctrl.Call(m, "Discovery")
	ret0, _ := ret[0].(discovery.DiscoveryInterface)
	return ret0
}

// Discovery indicates an expected call of Discovery
func (mr *MockInterfaceMockRecorder) Discovery() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discovery", reflect.TypeOf((*MockInterface)(nil).Discovery))
}

// Wing mocks base method
func (m *MockInterface) Wing() v1alpha1.WingV1alpha1Interface {
	ret := m.ctrl.Call(m, "Wing")
	ret0, _ := ret[0].(v1alpha1.WingV1alpha1Interface)
	return ret0
}

// Wing indicates an expected call of Wing
func (mr *MockInterfaceMockRecorder) Wing() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wing", reflect.TypeOf((*MockInterface)(nil).Wing))
}

// WingV1alpha1 mocks base method
func (m *MockInterface) WingV1alpha1() v1alpha1.WingV1alpha1Interface {
	ret := m.ctrl.Call(m, "WingV1alpha1")
	ret0, _ := ret[0].(v1alpha1.WingV1alpha1Interface)
	return ret0
}

// WingV1alpha1 indicates an expected call of WingV1alpha1
func (mr *MockInterfaceMockRecorder) WingV1alpha1() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WingV1alpha1", reflect.TypeOf((*MockInterface)(nil).WingV1alpha1))
}
