// Copyright Jetstack Ltd. See LICENSE for details.

// This file was automatically generated by lister-gen

package v1alpha1

// InstanceListerExpansion allows custom methods to be added to
// InstanceLister.
type InstanceListerExpansion interface{}

// InstanceNamespaceListerExpansion allows custom methods to be added to
// InstanceNamespaceLister.
type InstanceNamespaceListerExpansion interface{}

// PuppetTargetListerExpansion allows custom methods to be added to
// PuppetTargetLister.
type PuppetTargetListerExpansion interface{}

// PuppetTargetNamespaceListerExpansion allows custom methods to be added to
// PuppetTargetNamespaceLister.
type PuppetTargetNamespaceListerExpansion interface{}

// WingJobListerExpansion allows custom methods to be added to
// WingJobLister.
type WingJobListerExpansion interface{}

// WingJobNamespaceListerExpansion allows custom methods to be added to
// WingJobNamespaceLister.
type WingJobNamespaceListerExpansion interface{}
