// Copyright Jetstack Ltd. See LICENSE for details.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// InstanceListerExpansion allows custom methods to be added to
// InstanceLister.
type InstanceListerExpansion interface{}

// InstanceNamespaceListerExpansion allows custom methods to be added to
// InstanceNamespaceLister.
type InstanceNamespaceListerExpansion interface{}
