// +build !ignore_autogenerated

// Copyright Jetstack Ltd. See LICENSE for details.

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	wing "github.com/jetstack/tarmak/pkg/apis/wing"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Machine_To_wing_Machine,
		Convert_wing_Machine_To_v1alpha1_Machine,
		Convert_v1alpha1_MachineList_To_wing_MachineList,
		Convert_wing_MachineList_To_v1alpha1_MachineList,
		Convert_v1alpha1_MachineSpec_To_wing_MachineSpec,
		Convert_wing_MachineSpec_To_v1alpha1_MachineSpec,
		Convert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest,
		Convert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest,
		Convert_v1alpha1_MachineStatus_To_wing_MachineStatus,
		Convert_wing_MachineStatus_To_v1alpha1_MachineStatus,
		Convert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest,
		Convert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest,
	)
}

func autoConvert_v1alpha1_Machine_To_wing_Machine(in *Machine, out *wing.Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.MachineID = in.MachineID
	out.MachinePool = in.MachinePool
	out.Spec = (*wing.MachineSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*wing.MachineStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v1alpha1_Machine_To_wing_Machine is an autogenerated conversion function.
func Convert_v1alpha1_Machine_To_wing_Machine(in *Machine, out *wing.Machine, s conversion.Scope) error {
	return autoConvert_v1alpha1_Machine_To_wing_Machine(in, out, s)
}

func autoConvert_wing_Machine_To_v1alpha1_Machine(in *wing.Machine, out *Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.MachineID = in.MachineID
	out.MachinePool = in.MachinePool
	out.Spec = (*MachineSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*MachineStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_wing_Machine_To_v1alpha1_Machine is an autogenerated conversion function.
func Convert_wing_Machine_To_v1alpha1_Machine(in *wing.Machine, out *Machine, s conversion.Scope) error {
	return autoConvert_wing_Machine_To_v1alpha1_Machine(in, out, s)
}

func autoConvert_v1alpha1_MachineList_To_wing_MachineList(in *MachineList, out *wing.MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineList_To_wing_MachineList is an autogenerated conversion function.
func Convert_v1alpha1_MachineList_To_wing_MachineList(in *MachineList, out *wing.MachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineList_To_wing_MachineList(in, out, s)
}

func autoConvert_wing_MachineList_To_v1alpha1_MachineList(in *wing.MachineList, out *MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_MachineList_To_v1alpha1_MachineList is an autogenerated conversion function.
func Convert_wing_MachineList_To_v1alpha1_MachineList(in *wing.MachineList, out *MachineList, s conversion.Scope) error {
	return autoConvert_wing_MachineList_To_v1alpha1_MachineList(in, out, s)
}

func autoConvert_v1alpha1_MachineSpec_To_wing_MachineSpec(in *MachineSpec, out *wing.MachineSpec, s conversion.Scope) error {
	out.Converge = (*wing.MachineSpecManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*wing.MachineSpecManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_v1alpha1_MachineSpec_To_wing_MachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSpec_To_wing_MachineSpec(in *MachineSpec, out *wing.MachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSpec_To_wing_MachineSpec(in, out, s)
}

func autoConvert_wing_MachineSpec_To_v1alpha1_MachineSpec(in *wing.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	out.Converge = (*MachineSpecManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*MachineSpecManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_wing_MachineSpec_To_v1alpha1_MachineSpec is an autogenerated conversion function.
func Convert_wing_MachineSpec_To_v1alpha1_MachineSpec(in *wing.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	return autoConvert_wing_MachineSpec_To_v1alpha1_MachineSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(in *MachineSpecManifest, out *wing.MachineSpecManifest, s conversion.Scope) error {
	out.Path = in.Path
	out.Hash = in.Hash
	out.RequestTimestamp = in.RequestTimestamp
	return nil
}

// Convert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest is an autogenerated conversion function.
func Convert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(in *MachineSpecManifest, out *wing.MachineSpecManifest, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(in, out, s)
}

func autoConvert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(in *wing.MachineSpecManifest, out *MachineSpecManifest, s conversion.Scope) error {
	out.Path = in.Path
	out.Hash = in.Hash
	out.RequestTimestamp = in.RequestTimestamp
	return nil
}

// Convert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest is an autogenerated conversion function.
func Convert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(in *wing.MachineSpecManifest, out *MachineSpecManifest, s conversion.Scope) error {
	return autoConvert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(in, out, s)
}

func autoConvert_v1alpha1_MachineStatus_To_wing_MachineStatus(in *MachineStatus, out *wing.MachineStatus, s conversion.Scope) error {
	out.Converge = (*wing.MachineStatusManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*wing.MachineStatusManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_v1alpha1_MachineStatus_To_wing_MachineStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineStatus_To_wing_MachineStatus(in *MachineStatus, out *wing.MachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStatus_To_wing_MachineStatus(in, out, s)
}

func autoConvert_wing_MachineStatus_To_v1alpha1_MachineStatus(in *wing.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	out.Converge = (*MachineStatusManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*MachineStatusManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_wing_MachineStatus_To_v1alpha1_MachineStatus is an autogenerated conversion function.
func Convert_wing_MachineStatus_To_v1alpha1_MachineStatus(in *wing.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	return autoConvert_wing_MachineStatus_To_v1alpha1_MachineStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(in *MachineStatusManifest, out *wing.MachineStatusManifest, s conversion.Scope) error {
	out.State = wing.MachineManifestState(in.State)
	out.Hash = in.Hash
	out.LastUpdateTimestamp = in.LastUpdateTimestamp
	out.Messages = *(*[]string)(unsafe.Pointer(&in.Messages))
	out.ExitCodes = *(*[]int)(unsafe.Pointer(&in.ExitCodes))
	return nil
}

// Convert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest is an autogenerated conversion function.
func Convert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(in *MachineStatusManifest, out *wing.MachineStatusManifest, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(in, out, s)
}

func autoConvert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(in *wing.MachineStatusManifest, out *MachineStatusManifest, s conversion.Scope) error {
	out.State = MachineManifestState(in.State)
	out.Hash = in.Hash
	out.LastUpdateTimestamp = in.LastUpdateTimestamp
	out.Messages = *(*[]string)(unsafe.Pointer(&in.Messages))
	out.ExitCodes = *(*[]int)(unsafe.Pointer(&in.ExitCodes))
	return nil
}

// Convert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest is an autogenerated conversion function.
func Convert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(in *wing.MachineStatusManifest, out *MachineStatusManifest, s conversion.Scope) error {
	return autoConvert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(in, out, s)
}
