// +build !ignore_autogenerated

// Copyright Jetstack Ltd. See LICENSE for details.

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	wing "github.com/jetstack/tarmak/pkg/apis/wing"
	common "github.com/jetstack/tarmak/pkg/apis/wing/common"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Machine_To_wing_Machine,
		Convert_wing_Machine_To_v1alpha1_Machine,
		Convert_v1alpha1_MachineDeployment_To_wing_MachineDeployment,
		Convert_wing_MachineDeployment_To_v1alpha1_MachineDeployment,
		Convert_v1alpha1_MachineDeploymentList_To_wing_MachineDeploymentList,
		Convert_wing_MachineDeploymentList_To_v1alpha1_MachineDeploymentList,
		Convert_v1alpha1_MachineDeploymentSpec_To_wing_MachineDeploymentSpec,
		Convert_wing_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec,
		Convert_v1alpha1_MachineDeploymentStatus_To_wing_MachineDeploymentStatus,
		Convert_wing_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus,
		Convert_v1alpha1_MachineDeploymentStrategy_To_wing_MachineDeploymentStrategy,
		Convert_wing_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy,
		Convert_v1alpha1_MachineList_To_wing_MachineList,
		Convert_wing_MachineList_To_v1alpha1_MachineList,
		Convert_v1alpha1_MachineRollingUpdateDeployment_To_wing_MachineRollingUpdateDeployment,
		Convert_wing_MachineRollingUpdateDeployment_To_v1alpha1_MachineRollingUpdateDeployment,
		Convert_v1alpha1_MachineSet_To_wing_MachineSet,
		Convert_wing_MachineSet_To_v1alpha1_MachineSet,
		Convert_v1alpha1_MachineSetList_To_wing_MachineSetList,
		Convert_wing_MachineSetList_To_v1alpha1_MachineSetList,
		Convert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec,
		Convert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec,
		Convert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus,
		Convert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus,
		Convert_v1alpha1_MachineSpec_To_wing_MachineSpec,
		Convert_wing_MachineSpec_To_v1alpha1_MachineSpec,
		Convert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest,
		Convert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest,
		Convert_v1alpha1_MachineStatus_To_wing_MachineStatus,
		Convert_wing_MachineStatus_To_v1alpha1_MachineStatus,
		Convert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest,
		Convert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest,
		Convert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec,
		Convert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec,
	)
}

func autoConvert_v1alpha1_Machine_To_wing_Machine(in *Machine, out *wing.Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*wing.MachineSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*wing.MachineStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v1alpha1_Machine_To_wing_Machine is an autogenerated conversion function.
func Convert_v1alpha1_Machine_To_wing_Machine(in *Machine, out *wing.Machine, s conversion.Scope) error {
	return autoConvert_v1alpha1_Machine_To_wing_Machine(in, out, s)
}

func autoConvert_wing_Machine_To_v1alpha1_Machine(in *wing.Machine, out *Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*MachineSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*MachineStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_wing_Machine_To_v1alpha1_Machine is an autogenerated conversion function.
func Convert_wing_Machine_To_v1alpha1_Machine(in *wing.Machine, out *Machine, s conversion.Scope) error {
	return autoConvert_wing_Machine_To_v1alpha1_Machine(in, out, s)
}

func autoConvert_v1alpha1_MachineDeployment_To_wing_MachineDeployment(in *MachineDeployment, out *wing.MachineDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*wing.MachineDeploymentSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*wing.MachineDeploymentStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v1alpha1_MachineDeployment_To_wing_MachineDeployment is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeployment_To_wing_MachineDeployment(in *MachineDeployment, out *wing.MachineDeployment, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeployment_To_wing_MachineDeployment(in, out, s)
}

func autoConvert_wing_MachineDeployment_To_v1alpha1_MachineDeployment(in *wing.MachineDeployment, out *MachineDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*MachineDeploymentSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*MachineDeploymentStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_wing_MachineDeployment_To_v1alpha1_MachineDeployment is an autogenerated conversion function.
func Convert_wing_MachineDeployment_To_v1alpha1_MachineDeployment(in *wing.MachineDeployment, out *MachineDeployment, s conversion.Scope) error {
	return autoConvert_wing_MachineDeployment_To_v1alpha1_MachineDeployment(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentList_To_wing_MachineDeploymentList(in *MachineDeploymentList, out *wing.MachineDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.MachineDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineDeploymentList_To_wing_MachineDeploymentList is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentList_To_wing_MachineDeploymentList(in *MachineDeploymentList, out *wing.MachineDeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentList_To_wing_MachineDeploymentList(in, out, s)
}

func autoConvert_wing_MachineDeploymentList_To_v1alpha1_MachineDeploymentList(in *wing.MachineDeploymentList, out *MachineDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MachineDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_MachineDeploymentList_To_v1alpha1_MachineDeploymentList is an autogenerated conversion function.
func Convert_wing_MachineDeploymentList_To_v1alpha1_MachineDeploymentList(in *wing.MachineDeploymentList, out *MachineDeploymentList, s conversion.Scope) error {
	return autoConvert_wing_MachineDeploymentList_To_v1alpha1_MachineDeploymentList(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentSpec_To_wing_MachineDeploymentSpec(in *MachineDeploymentSpec, out *wing.MachineDeploymentSpec, s conversion.Scope) error {
	out.MinReplicas = (*int32)(unsafe.Pointer(in.MinReplicas))
	out.MaxReplicas = (*int32)(unsafe.Pointer(in.MaxReplicas))
	out.Selector = in.Selector
	if err := Convert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	out.Strategy = (*wing.MachineDeploymentStrategy)(unsafe.Pointer(in.Strategy))
	out.MinReadySeconds = (*int32)(unsafe.Pointer(in.MinReadySeconds))
	out.RevisionHistoryLimit = (*int32)(unsafe.Pointer(in.RevisionHistoryLimit))
	out.Paused = in.Paused
	out.ProgressDeadlineSeconds = (*int32)(unsafe.Pointer(in.ProgressDeadlineSeconds))
	return nil
}

// Convert_v1alpha1_MachineDeploymentSpec_To_wing_MachineDeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentSpec_To_wing_MachineDeploymentSpec(in *MachineDeploymentSpec, out *wing.MachineDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentSpec_To_wing_MachineDeploymentSpec(in, out, s)
}

func autoConvert_wing_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec(in *wing.MachineDeploymentSpec, out *MachineDeploymentSpec, s conversion.Scope) error {
	out.MinReplicas = (*int32)(unsafe.Pointer(in.MinReplicas))
	out.MaxReplicas = (*int32)(unsafe.Pointer(in.MaxReplicas))
	out.Selector = in.Selector
	if err := Convert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	out.Strategy = (*MachineDeploymentStrategy)(unsafe.Pointer(in.Strategy))
	out.MinReadySeconds = (*int32)(unsafe.Pointer(in.MinReadySeconds))
	out.RevisionHistoryLimit = (*int32)(unsafe.Pointer(in.RevisionHistoryLimit))
	out.Paused = in.Paused
	out.ProgressDeadlineSeconds = (*int32)(unsafe.Pointer(in.ProgressDeadlineSeconds))
	return nil
}

// Convert_wing_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec is an autogenerated conversion function.
func Convert_wing_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec(in *wing.MachineDeploymentSpec, out *MachineDeploymentSpec, s conversion.Scope) error {
	return autoConvert_wing_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentStatus_To_wing_MachineDeploymentStatus(in *MachineDeploymentStatus, out *wing.MachineDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Replicas = in.Replicas
	out.UpdatedReplicas = in.UpdatedReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	return nil
}

// Convert_v1alpha1_MachineDeploymentStatus_To_wing_MachineDeploymentStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentStatus_To_wing_MachineDeploymentStatus(in *MachineDeploymentStatus, out *wing.MachineDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentStatus_To_wing_MachineDeploymentStatus(in, out, s)
}

func autoConvert_wing_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus(in *wing.MachineDeploymentStatus, out *MachineDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Replicas = in.Replicas
	out.UpdatedReplicas = in.UpdatedReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	return nil
}

// Convert_wing_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus is an autogenerated conversion function.
func Convert_wing_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus(in *wing.MachineDeploymentStatus, out *MachineDeploymentStatus, s conversion.Scope) error {
	return autoConvert_wing_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentStrategy_To_wing_MachineDeploymentStrategy(in *MachineDeploymentStrategy, out *wing.MachineDeploymentStrategy, s conversion.Scope) error {
	out.Type = common.MachineDeploymentStrategyType(in.Type)
	out.RollingUpdate = (*wing.MachineRollingUpdateDeployment)(unsafe.Pointer(in.RollingUpdate))
	return nil
}

// Convert_v1alpha1_MachineDeploymentStrategy_To_wing_MachineDeploymentStrategy is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentStrategy_To_wing_MachineDeploymentStrategy(in *MachineDeploymentStrategy, out *wing.MachineDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentStrategy_To_wing_MachineDeploymentStrategy(in, out, s)
}

func autoConvert_wing_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy(in *wing.MachineDeploymentStrategy, out *MachineDeploymentStrategy, s conversion.Scope) error {
	out.Type = common.MachineDeploymentStrategyType(in.Type)
	out.RollingUpdate = (*MachineRollingUpdateDeployment)(unsafe.Pointer(in.RollingUpdate))
	return nil
}

// Convert_wing_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy is an autogenerated conversion function.
func Convert_wing_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy(in *wing.MachineDeploymentStrategy, out *MachineDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_wing_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy(in, out, s)
}

func autoConvert_v1alpha1_MachineList_To_wing_MachineList(in *MachineList, out *wing.MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineList_To_wing_MachineList is an autogenerated conversion function.
func Convert_v1alpha1_MachineList_To_wing_MachineList(in *MachineList, out *wing.MachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineList_To_wing_MachineList(in, out, s)
}

func autoConvert_wing_MachineList_To_v1alpha1_MachineList(in *wing.MachineList, out *MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_MachineList_To_v1alpha1_MachineList is an autogenerated conversion function.
func Convert_wing_MachineList_To_v1alpha1_MachineList(in *wing.MachineList, out *MachineList, s conversion.Scope) error {
	return autoConvert_wing_MachineList_To_v1alpha1_MachineList(in, out, s)
}

func autoConvert_v1alpha1_MachineRollingUpdateDeployment_To_wing_MachineRollingUpdateDeployment(in *MachineRollingUpdateDeployment, out *wing.MachineRollingUpdateDeployment, s conversion.Scope) error {
	out.MaxUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnavailable))
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	return nil
}

// Convert_v1alpha1_MachineRollingUpdateDeployment_To_wing_MachineRollingUpdateDeployment is an autogenerated conversion function.
func Convert_v1alpha1_MachineRollingUpdateDeployment_To_wing_MachineRollingUpdateDeployment(in *MachineRollingUpdateDeployment, out *wing.MachineRollingUpdateDeployment, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineRollingUpdateDeployment_To_wing_MachineRollingUpdateDeployment(in, out, s)
}

func autoConvert_wing_MachineRollingUpdateDeployment_To_v1alpha1_MachineRollingUpdateDeployment(in *wing.MachineRollingUpdateDeployment, out *MachineRollingUpdateDeployment, s conversion.Scope) error {
	out.MaxUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnavailable))
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	return nil
}

// Convert_wing_MachineRollingUpdateDeployment_To_v1alpha1_MachineRollingUpdateDeployment is an autogenerated conversion function.
func Convert_wing_MachineRollingUpdateDeployment_To_v1alpha1_MachineRollingUpdateDeployment(in *wing.MachineRollingUpdateDeployment, out *MachineRollingUpdateDeployment, s conversion.Scope) error {
	return autoConvert_wing_MachineRollingUpdateDeployment_To_v1alpha1_MachineRollingUpdateDeployment(in, out, s)
}

func autoConvert_v1alpha1_MachineSet_To_wing_MachineSet(in *MachineSet, out *wing.MachineSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*wing.MachineSetSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*wing.MachineSetStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v1alpha1_MachineSet_To_wing_MachineSet is an autogenerated conversion function.
func Convert_v1alpha1_MachineSet_To_wing_MachineSet(in *MachineSet, out *wing.MachineSet, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSet_To_wing_MachineSet(in, out, s)
}

func autoConvert_wing_MachineSet_To_v1alpha1_MachineSet(in *wing.MachineSet, out *MachineSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*MachineSetSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*MachineSetStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_wing_MachineSet_To_v1alpha1_MachineSet is an autogenerated conversion function.
func Convert_wing_MachineSet_To_v1alpha1_MachineSet(in *wing.MachineSet, out *MachineSet, s conversion.Scope) error {
	return autoConvert_wing_MachineSet_To_v1alpha1_MachineSet(in, out, s)
}

func autoConvert_v1alpha1_MachineSetList_To_wing_MachineSetList(in *MachineSetList, out *wing.MachineSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.MachineSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineSetList_To_wing_MachineSetList is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetList_To_wing_MachineSetList(in *MachineSetList, out *wing.MachineSetList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetList_To_wing_MachineSetList(in, out, s)
}

func autoConvert_wing_MachineSetList_To_v1alpha1_MachineSetList(in *wing.MachineSetList, out *MachineSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MachineSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_MachineSetList_To_v1alpha1_MachineSetList is an autogenerated conversion function.
func Convert_wing_MachineSetList_To_v1alpha1_MachineSetList(in *wing.MachineSetList, out *MachineSetList, s conversion.Scope) error {
	return autoConvert_wing_MachineSetList_To_v1alpha1_MachineSetList(in, out, s)
}

func autoConvert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec(in *MachineSetSpec, out *wing.MachineSetSpec, s conversion.Scope) error {
	out.MinReplicas = (*int32)(unsafe.Pointer(in.MinReplicas))
	out.MaxReplicas = (*int32)(unsafe.Pointer(in.MaxReplicas))
	out.MinReadySeconds = in.MinReadySeconds
	out.Selector = in.Selector
	if err := Convert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec(in *MachineSetSpec, out *wing.MachineSetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec(in, out, s)
}

func autoConvert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec(in *wing.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	out.MinReplicas = (*int32)(unsafe.Pointer(in.MinReplicas))
	out.MaxReplicas = (*int32)(unsafe.Pointer(in.MaxReplicas))
	out.MinReadySeconds = in.MinReadySeconds
	out.Selector = in.Selector
	if err := Convert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec is an autogenerated conversion function.
func Convert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec(in *wing.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	return autoConvert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus(in *MachineSetStatus, out *wing.MachineSetStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.FullyLabeledReplicas = in.FullyLabeledReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.ObservedGeneration = in.ObservedGeneration
	out.ErrorReason = common.MachineStatusError(in.ErrorReason)
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	return nil
}

// Convert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus(in *MachineSetStatus, out *wing.MachineSetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus(in, out, s)
}

func autoConvert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus(in *wing.MachineSetStatus, out *MachineSetStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.FullyLabeledReplicas = in.FullyLabeledReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.ObservedGeneration = in.ObservedGeneration
	out.ErrorReason = common.MachineStatusError(in.ErrorReason)
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	return nil
}

// Convert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus is an autogenerated conversion function.
func Convert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus(in *wing.MachineSetStatus, out *MachineSetStatus, s conversion.Scope) error {
	return autoConvert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineSpec_To_wing_MachineSpec(in *MachineSpec, out *wing.MachineSpec, s conversion.Scope) error {
	out.Converge = (*wing.MachineSpecManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*wing.MachineSpecManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_v1alpha1_MachineSpec_To_wing_MachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSpec_To_wing_MachineSpec(in *MachineSpec, out *wing.MachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSpec_To_wing_MachineSpec(in, out, s)
}

func autoConvert_wing_MachineSpec_To_v1alpha1_MachineSpec(in *wing.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	out.Converge = (*MachineSpecManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*MachineSpecManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_wing_MachineSpec_To_v1alpha1_MachineSpec is an autogenerated conversion function.
func Convert_wing_MachineSpec_To_v1alpha1_MachineSpec(in *wing.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	return autoConvert_wing_MachineSpec_To_v1alpha1_MachineSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(in *MachineSpecManifest, out *wing.MachineSpecManifest, s conversion.Scope) error {
	out.Path = in.Path
	out.Hash = in.Hash
	out.RequestTimestamp = in.RequestTimestamp
	return nil
}

// Convert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest is an autogenerated conversion function.
func Convert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(in *MachineSpecManifest, out *wing.MachineSpecManifest, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(in, out, s)
}

func autoConvert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(in *wing.MachineSpecManifest, out *MachineSpecManifest, s conversion.Scope) error {
	out.Path = in.Path
	out.Hash = in.Hash
	out.RequestTimestamp = in.RequestTimestamp
	return nil
}

// Convert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest is an autogenerated conversion function.
func Convert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(in *wing.MachineSpecManifest, out *MachineSpecManifest, s conversion.Scope) error {
	return autoConvert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(in, out, s)
}

func autoConvert_v1alpha1_MachineStatus_To_wing_MachineStatus(in *MachineStatus, out *wing.MachineStatus, s conversion.Scope) error {
	out.Converge = (*wing.MachineStatusManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*wing.MachineStatusManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_v1alpha1_MachineStatus_To_wing_MachineStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineStatus_To_wing_MachineStatus(in *MachineStatus, out *wing.MachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStatus_To_wing_MachineStatus(in, out, s)
}

func autoConvert_wing_MachineStatus_To_v1alpha1_MachineStatus(in *wing.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	out.Converge = (*MachineStatusManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*MachineStatusManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_wing_MachineStatus_To_v1alpha1_MachineStatus is an autogenerated conversion function.
func Convert_wing_MachineStatus_To_v1alpha1_MachineStatus(in *wing.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	return autoConvert_wing_MachineStatus_To_v1alpha1_MachineStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(in *MachineStatusManifest, out *wing.MachineStatusManifest, s conversion.Scope) error {
	out.State = wing.MachineManifestState(in.State)
	out.Hash = in.Hash
	out.LastUpdateTimestamp = in.LastUpdateTimestamp
	out.Messages = *(*[]string)(unsafe.Pointer(&in.Messages))
	out.ExitCodes = *(*[]int)(unsafe.Pointer(&in.ExitCodes))
	return nil
}

// Convert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest is an autogenerated conversion function.
func Convert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(in *MachineStatusManifest, out *wing.MachineStatusManifest, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(in, out, s)
}

func autoConvert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(in *wing.MachineStatusManifest, out *MachineStatusManifest, s conversion.Scope) error {
	out.State = MachineManifestState(in.State)
	out.Hash = in.Hash
	out.LastUpdateTimestamp = in.LastUpdateTimestamp
	out.Messages = *(*[]string)(unsafe.Pointer(&in.Messages))
	out.ExitCodes = *(*[]int)(unsafe.Pointer(&in.ExitCodes))
	return nil
}

// Convert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest is an autogenerated conversion function.
func Convert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(in *wing.MachineStatusManifest, out *MachineStatusManifest, s conversion.Scope) error {
	return autoConvert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(in, out, s)
}

func autoConvert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(in *MachineTemplateSpec, out *wing.MachineTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineSpec_To_wing_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(in *MachineTemplateSpec, out *wing.MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(in, out, s)
}

func autoConvert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(in *wing.MachineTemplateSpec, out *MachineTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_wing_MachineSpec_To_v1alpha1_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec is an autogenerated conversion function.
func Convert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(in *wing.MachineTemplateSpec, out *MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(in, out, s)
}
