// +build !ignore_autogenerated

// Copyright Jetstack Ltd. See LICENSE for details.

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	wing "github.com/jetstack/tarmak/pkg/apis/wing"
	clustercommon "github.com/jetstack/tarmak/pkg/apis/wing/clustercommon"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_FileManifestSource_To_wing_FileManifestSource,
		Convert_wing_FileManifestSource_To_v1alpha1_FileManifestSource,
		Convert_v1alpha1_Instance_To_wing_Instance,
		Convert_wing_Instance_To_v1alpha1_Instance,
		Convert_v1alpha1_InstanceList_To_wing_InstanceList,
		Convert_wing_InstanceList_To_v1alpha1_InstanceList,
		Convert_v1alpha1_InstanceSpec_To_wing_InstanceSpec,
		Convert_wing_InstanceSpec_To_v1alpha1_InstanceSpec,
		Convert_v1alpha1_InstanceStatus_To_wing_InstanceStatus,
		Convert_wing_InstanceStatus_To_v1alpha1_InstanceStatus,
		Convert_v1alpha1_Machine_To_wing_Machine,
		Convert_wing_Machine_To_v1alpha1_Machine,
		Convert_v1alpha1_MachineList_To_wing_MachineList,
		Convert_wing_MachineList_To_v1alpha1_MachineList,
		Convert_v1alpha1_MachineSpec_To_wing_MachineSpec,
		Convert_wing_MachineSpec_To_v1alpha1_MachineSpec,
		Convert_v1alpha1_MachineStatus_To_wing_MachineStatus,
		Convert_wing_MachineStatus_To_v1alpha1_MachineStatus,
		Convert_v1alpha1_MachineVersionInfo_To_wing_MachineVersionInfo,
		Convert_wing_MachineVersionInfo_To_v1alpha1_MachineVersionInfo,
		Convert_v1alpha1_ManifestSource_To_wing_ManifestSource,
		Convert_wing_ManifestSource_To_v1alpha1_ManifestSource,
		Convert_v1alpha1_ProviderConfig_To_wing_ProviderConfig,
		Convert_wing_ProviderConfig_To_v1alpha1_ProviderConfig,
		Convert_v1alpha1_ProviderConfigSource_To_wing_ProviderConfigSource,
		Convert_wing_ProviderConfigSource_To_v1alpha1_ProviderConfigSource,
		Convert_v1alpha1_PuppetTarget_To_wing_PuppetTarget,
		Convert_wing_PuppetTarget_To_v1alpha1_PuppetTarget,
		Convert_v1alpha1_PuppetTargetList_To_wing_PuppetTargetList,
		Convert_wing_PuppetTargetList_To_v1alpha1_PuppetTargetList,
		Convert_v1alpha1_S3ManifestSource_To_wing_S3ManifestSource,
		Convert_wing_S3ManifestSource_To_v1alpha1_S3ManifestSource,
		Convert_v1alpha1_WingJob_To_wing_WingJob,
		Convert_wing_WingJob_To_v1alpha1_WingJob,
		Convert_v1alpha1_WingJobList_To_wing_WingJobList,
		Convert_wing_WingJobList_To_v1alpha1_WingJobList,
		Convert_v1alpha1_WingJobSpec_To_wing_WingJobSpec,
		Convert_wing_WingJobSpec_To_v1alpha1_WingJobSpec,
		Convert_v1alpha1_WingJobStatus_To_wing_WingJobStatus,
		Convert_wing_WingJobStatus_To_v1alpha1_WingJobStatus,
	)
}

func autoConvert_v1alpha1_FileManifestSource_To_wing_FileManifestSource(in *FileManifestSource, out *wing.FileManifestSource, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_FileManifestSource_To_wing_FileManifestSource is an autogenerated conversion function.
func Convert_v1alpha1_FileManifestSource_To_wing_FileManifestSource(in *FileManifestSource, out *wing.FileManifestSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileManifestSource_To_wing_FileManifestSource(in, out, s)
}

func autoConvert_wing_FileManifestSource_To_v1alpha1_FileManifestSource(in *wing.FileManifestSource, out *FileManifestSource, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_wing_FileManifestSource_To_v1alpha1_FileManifestSource is an autogenerated conversion function.
func Convert_wing_FileManifestSource_To_v1alpha1_FileManifestSource(in *wing.FileManifestSource, out *FileManifestSource, s conversion.Scope) error {
	return autoConvert_wing_FileManifestSource_To_v1alpha1_FileManifestSource(in, out, s)
}

func autoConvert_v1alpha1_Instance_To_wing_Instance(in *Instance, out *wing.Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.InstanceID = in.InstanceID
	out.InstancePool = in.InstancePool
	out.Spec = (*wing.InstanceSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*wing.InstanceStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v1alpha1_Instance_To_wing_Instance is an autogenerated conversion function.
func Convert_v1alpha1_Instance_To_wing_Instance(in *Instance, out *wing.Instance, s conversion.Scope) error {
	return autoConvert_v1alpha1_Instance_To_wing_Instance(in, out, s)
}

func autoConvert_wing_Instance_To_v1alpha1_Instance(in *wing.Instance, out *Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.InstanceID = in.InstanceID
	out.InstancePool = in.InstancePool
	out.Spec = (*InstanceSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*InstanceStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_wing_Instance_To_v1alpha1_Instance is an autogenerated conversion function.
func Convert_wing_Instance_To_v1alpha1_Instance(in *wing.Instance, out *Instance, s conversion.Scope) error {
	return autoConvert_wing_Instance_To_v1alpha1_Instance(in, out, s)
}

func autoConvert_v1alpha1_InstanceList_To_wing_InstanceList(in *InstanceList, out *wing.InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_InstanceList_To_wing_InstanceList is an autogenerated conversion function.
func Convert_v1alpha1_InstanceList_To_wing_InstanceList(in *InstanceList, out *wing.InstanceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceList_To_wing_InstanceList(in, out, s)
}

func autoConvert_wing_InstanceList_To_v1alpha1_InstanceList(in *wing.InstanceList, out *InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_InstanceList_To_v1alpha1_InstanceList is an autogenerated conversion function.
func Convert_wing_InstanceList_To_v1alpha1_InstanceList(in *wing.InstanceList, out *InstanceList, s conversion.Scope) error {
	return autoConvert_wing_InstanceList_To_v1alpha1_InstanceList(in, out, s)
}

func autoConvert_v1alpha1_InstanceSpec_To_wing_InstanceSpec(in *InstanceSpec, out *wing.InstanceSpec, s conversion.Scope) error {
	out.PuppetTargetRef = in.PuppetTargetRef
	return nil
}

// Convert_v1alpha1_InstanceSpec_To_wing_InstanceSpec is an autogenerated conversion function.
func Convert_v1alpha1_InstanceSpec_To_wing_InstanceSpec(in *InstanceSpec, out *wing.InstanceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceSpec_To_wing_InstanceSpec(in, out, s)
}

func autoConvert_wing_InstanceSpec_To_v1alpha1_InstanceSpec(in *wing.InstanceSpec, out *InstanceSpec, s conversion.Scope) error {
	out.PuppetTargetRef = in.PuppetTargetRef
	return nil
}

// Convert_wing_InstanceSpec_To_v1alpha1_InstanceSpec is an autogenerated conversion function.
func Convert_wing_InstanceSpec_To_v1alpha1_InstanceSpec(in *wing.InstanceSpec, out *InstanceSpec, s conversion.Scope) error {
	return autoConvert_wing_InstanceSpec_To_v1alpha1_InstanceSpec(in, out, s)
}

func autoConvert_v1alpha1_InstanceStatus_To_wing_InstanceStatus(in *InstanceStatus, out *wing.InstanceStatus, s conversion.Scope) error {
	out.PuppetTargetRef = in.PuppetTargetRef
	out.Converged = in.Converged
	return nil
}

// Convert_v1alpha1_InstanceStatus_To_wing_InstanceStatus is an autogenerated conversion function.
func Convert_v1alpha1_InstanceStatus_To_wing_InstanceStatus(in *InstanceStatus, out *wing.InstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceStatus_To_wing_InstanceStatus(in, out, s)
}

func autoConvert_wing_InstanceStatus_To_v1alpha1_InstanceStatus(in *wing.InstanceStatus, out *InstanceStatus, s conversion.Scope) error {
	out.PuppetTargetRef = in.PuppetTargetRef
	out.Converged = in.Converged
	return nil
}

// Convert_wing_InstanceStatus_To_v1alpha1_InstanceStatus is an autogenerated conversion function.
func Convert_wing_InstanceStatus_To_v1alpha1_InstanceStatus(in *wing.InstanceStatus, out *InstanceStatus, s conversion.Scope) error {
	return autoConvert_wing_InstanceStatus_To_v1alpha1_InstanceStatus(in, out, s)
}

func autoConvert_v1alpha1_Machine_To_wing_Machine(in *Machine, out *wing.Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineSpec_To_wing_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MachineStatus_To_wing_MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Machine_To_wing_Machine is an autogenerated conversion function.
func Convert_v1alpha1_Machine_To_wing_Machine(in *Machine, out *wing.Machine, s conversion.Scope) error {
	return autoConvert_v1alpha1_Machine_To_wing_Machine(in, out, s)
}

func autoConvert_wing_Machine_To_v1alpha1_Machine(in *wing.Machine, out *Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_wing_MachineSpec_To_v1alpha1_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_wing_MachineStatus_To_v1alpha1_MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_wing_Machine_To_v1alpha1_Machine is an autogenerated conversion function.
func Convert_wing_Machine_To_v1alpha1_Machine(in *wing.Machine, out *Machine, s conversion.Scope) error {
	return autoConvert_wing_Machine_To_v1alpha1_Machine(in, out, s)
}

func autoConvert_v1alpha1_MachineList_To_wing_MachineList(in *MachineList, out *wing.MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineList_To_wing_MachineList is an autogenerated conversion function.
func Convert_v1alpha1_MachineList_To_wing_MachineList(in *MachineList, out *wing.MachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineList_To_wing_MachineList(in, out, s)
}

func autoConvert_wing_MachineList_To_v1alpha1_MachineList(in *wing.MachineList, out *MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_MachineList_To_v1alpha1_MachineList is an autogenerated conversion function.
func Convert_wing_MachineList_To_v1alpha1_MachineList(in *wing.MachineList, out *MachineList, s conversion.Scope) error {
	return autoConvert_wing_MachineList_To_v1alpha1_MachineList(in, out, s)
}

func autoConvert_v1alpha1_MachineSpec_To_wing_MachineSpec(in *MachineSpec, out *wing.MachineSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Taints = *(*[]v1.Taint)(unsafe.Pointer(&in.Taints))
	if err := Convert_v1alpha1_ProviderConfig_To_wing_ProviderConfig(&in.ProviderConfig, &out.ProviderConfig, s); err != nil {
		return err
	}
	out.Roles = *(*[]clustercommon.MachineRole)(unsafe.Pointer(&in.Roles))
	if err := Convert_v1alpha1_MachineVersionInfo_To_wing_MachineVersionInfo(&in.Versions, &out.Versions, s); err != nil {
		return err
	}
	out.ConfigSource = (*v1.NodeConfigSource)(unsafe.Pointer(in.ConfigSource))
	out.PuppetTargetRef = in.PuppetTargetRef
	return nil
}

// Convert_v1alpha1_MachineSpec_To_wing_MachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSpec_To_wing_MachineSpec(in *MachineSpec, out *wing.MachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSpec_To_wing_MachineSpec(in, out, s)
}

func autoConvert_wing_MachineSpec_To_v1alpha1_MachineSpec(in *wing.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Taints = *(*[]v1.Taint)(unsafe.Pointer(&in.Taints))
	if err := Convert_wing_ProviderConfig_To_v1alpha1_ProviderConfig(&in.ProviderConfig, &out.ProviderConfig, s); err != nil {
		return err
	}
	out.Roles = *(*[]clustercommon.MachineRole)(unsafe.Pointer(&in.Roles))
	if err := Convert_wing_MachineVersionInfo_To_v1alpha1_MachineVersionInfo(&in.Versions, &out.Versions, s); err != nil {
		return err
	}
	out.ConfigSource = (*v1.NodeConfigSource)(unsafe.Pointer(in.ConfigSource))
	out.PuppetTargetRef = in.PuppetTargetRef
	return nil
}

// Convert_wing_MachineSpec_To_v1alpha1_MachineSpec is an autogenerated conversion function.
func Convert_wing_MachineSpec_To_v1alpha1_MachineSpec(in *wing.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	return autoConvert_wing_MachineSpec_To_v1alpha1_MachineSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineStatus_To_wing_MachineStatus(in *MachineStatus, out *wing.MachineStatus, s conversion.Scope) error {
	out.NodeRef = (*v1.ObjectReference)(unsafe.Pointer(in.NodeRef))
	out.LastUpdated = in.LastUpdated
	out.Versions = (*wing.MachineVersionInfo)(unsafe.Pointer(in.Versions))
	out.ErrorReason = (*clustercommon.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.ProviderStatus = (*runtime.RawExtension)(unsafe.Pointer(in.ProviderStatus))
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.Converged = in.Converged
	return nil
}

// Convert_v1alpha1_MachineStatus_To_wing_MachineStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineStatus_To_wing_MachineStatus(in *MachineStatus, out *wing.MachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStatus_To_wing_MachineStatus(in, out, s)
}

func autoConvert_wing_MachineStatus_To_v1alpha1_MachineStatus(in *wing.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	out.NodeRef = (*v1.ObjectReference)(unsafe.Pointer(in.NodeRef))
	out.LastUpdated = in.LastUpdated
	out.Versions = (*MachineVersionInfo)(unsafe.Pointer(in.Versions))
	out.ErrorReason = (*clustercommon.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.ProviderStatus = (*runtime.RawExtension)(unsafe.Pointer(in.ProviderStatus))
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.Converged = in.Converged
	return nil
}

// Convert_wing_MachineStatus_To_v1alpha1_MachineStatus is an autogenerated conversion function.
func Convert_wing_MachineStatus_To_v1alpha1_MachineStatus(in *wing.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	return autoConvert_wing_MachineStatus_To_v1alpha1_MachineStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineVersionInfo_To_wing_MachineVersionInfo(in *MachineVersionInfo, out *wing.MachineVersionInfo, s conversion.Scope) error {
	out.Kubelet = in.Kubelet
	out.ControlPlane = in.ControlPlane
	return nil
}

// Convert_v1alpha1_MachineVersionInfo_To_wing_MachineVersionInfo is an autogenerated conversion function.
func Convert_v1alpha1_MachineVersionInfo_To_wing_MachineVersionInfo(in *MachineVersionInfo, out *wing.MachineVersionInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineVersionInfo_To_wing_MachineVersionInfo(in, out, s)
}

func autoConvert_wing_MachineVersionInfo_To_v1alpha1_MachineVersionInfo(in *wing.MachineVersionInfo, out *MachineVersionInfo, s conversion.Scope) error {
	out.Kubelet = in.Kubelet
	out.ControlPlane = in.ControlPlane
	return nil
}

// Convert_wing_MachineVersionInfo_To_v1alpha1_MachineVersionInfo is an autogenerated conversion function.
func Convert_wing_MachineVersionInfo_To_v1alpha1_MachineVersionInfo(in *wing.MachineVersionInfo, out *MachineVersionInfo, s conversion.Scope) error {
	return autoConvert_wing_MachineVersionInfo_To_v1alpha1_MachineVersionInfo(in, out, s)
}

func autoConvert_v1alpha1_ManifestSource_To_wing_ManifestSource(in *ManifestSource, out *wing.ManifestSource, s conversion.Scope) error {
	out.S3 = (*wing.S3ManifestSource)(unsafe.Pointer(in.S3))
	out.File = (*wing.FileManifestSource)(unsafe.Pointer(in.File))
	return nil
}

// Convert_v1alpha1_ManifestSource_To_wing_ManifestSource is an autogenerated conversion function.
func Convert_v1alpha1_ManifestSource_To_wing_ManifestSource(in *ManifestSource, out *wing.ManifestSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ManifestSource_To_wing_ManifestSource(in, out, s)
}

func autoConvert_wing_ManifestSource_To_v1alpha1_ManifestSource(in *wing.ManifestSource, out *ManifestSource, s conversion.Scope) error {
	out.S3 = (*S3ManifestSource)(unsafe.Pointer(in.S3))
	out.File = (*FileManifestSource)(unsafe.Pointer(in.File))
	return nil
}

// Convert_wing_ManifestSource_To_v1alpha1_ManifestSource is an autogenerated conversion function.
func Convert_wing_ManifestSource_To_v1alpha1_ManifestSource(in *wing.ManifestSource, out *ManifestSource, s conversion.Scope) error {
	return autoConvert_wing_ManifestSource_To_v1alpha1_ManifestSource(in, out, s)
}

func autoConvert_v1alpha1_ProviderConfig_To_wing_ProviderConfig(in *ProviderConfig, out *wing.ProviderConfig, s conversion.Scope) error {
	out.Value = (*runtime.RawExtension)(unsafe.Pointer(in.Value))
	out.ValueFrom = (*wing.ProviderConfigSource)(unsafe.Pointer(in.ValueFrom))
	return nil
}

// Convert_v1alpha1_ProviderConfig_To_wing_ProviderConfig is an autogenerated conversion function.
func Convert_v1alpha1_ProviderConfig_To_wing_ProviderConfig(in *ProviderConfig, out *wing.ProviderConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProviderConfig_To_wing_ProviderConfig(in, out, s)
}

func autoConvert_wing_ProviderConfig_To_v1alpha1_ProviderConfig(in *wing.ProviderConfig, out *ProviderConfig, s conversion.Scope) error {
	out.Value = (*runtime.RawExtension)(unsafe.Pointer(in.Value))
	out.ValueFrom = (*ProviderConfigSource)(unsafe.Pointer(in.ValueFrom))
	return nil
}

// Convert_wing_ProviderConfig_To_v1alpha1_ProviderConfig is an autogenerated conversion function.
func Convert_wing_ProviderConfig_To_v1alpha1_ProviderConfig(in *wing.ProviderConfig, out *ProviderConfig, s conversion.Scope) error {
	return autoConvert_wing_ProviderConfig_To_v1alpha1_ProviderConfig(in, out, s)
}

func autoConvert_v1alpha1_ProviderConfigSource_To_wing_ProviderConfigSource(in *ProviderConfigSource, out *wing.ProviderConfigSource, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ProviderConfigSource_To_wing_ProviderConfigSource is an autogenerated conversion function.
func Convert_v1alpha1_ProviderConfigSource_To_wing_ProviderConfigSource(in *ProviderConfigSource, out *wing.ProviderConfigSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProviderConfigSource_To_wing_ProviderConfigSource(in, out, s)
}

func autoConvert_wing_ProviderConfigSource_To_v1alpha1_ProviderConfigSource(in *wing.ProviderConfigSource, out *ProviderConfigSource, s conversion.Scope) error {
	return nil
}

// Convert_wing_ProviderConfigSource_To_v1alpha1_ProviderConfigSource is an autogenerated conversion function.
func Convert_wing_ProviderConfigSource_To_v1alpha1_ProviderConfigSource(in *wing.ProviderConfigSource, out *ProviderConfigSource, s conversion.Scope) error {
	return autoConvert_wing_ProviderConfigSource_To_v1alpha1_ProviderConfigSource(in, out, s)
}

func autoConvert_v1alpha1_PuppetTarget_To_wing_PuppetTarget(in *PuppetTarget, out *wing.PuppetTarget, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ManifestSource_To_wing_ManifestSource(&in.Source, &out.Source, s); err != nil {
		return err
	}
	out.Hash = in.Hash
	return nil
}

// Convert_v1alpha1_PuppetTarget_To_wing_PuppetTarget is an autogenerated conversion function.
func Convert_v1alpha1_PuppetTarget_To_wing_PuppetTarget(in *PuppetTarget, out *wing.PuppetTarget, s conversion.Scope) error {
	return autoConvert_v1alpha1_PuppetTarget_To_wing_PuppetTarget(in, out, s)
}

func autoConvert_wing_PuppetTarget_To_v1alpha1_PuppetTarget(in *wing.PuppetTarget, out *PuppetTarget, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_wing_ManifestSource_To_v1alpha1_ManifestSource(&in.Source, &out.Source, s); err != nil {
		return err
	}
	out.Hash = in.Hash
	return nil
}

// Convert_wing_PuppetTarget_To_v1alpha1_PuppetTarget is an autogenerated conversion function.
func Convert_wing_PuppetTarget_To_v1alpha1_PuppetTarget(in *wing.PuppetTarget, out *PuppetTarget, s conversion.Scope) error {
	return autoConvert_wing_PuppetTarget_To_v1alpha1_PuppetTarget(in, out, s)
}

func autoConvert_v1alpha1_PuppetTargetList_To_wing_PuppetTargetList(in *PuppetTargetList, out *wing.PuppetTargetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.PuppetTarget)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PuppetTargetList_To_wing_PuppetTargetList is an autogenerated conversion function.
func Convert_v1alpha1_PuppetTargetList_To_wing_PuppetTargetList(in *PuppetTargetList, out *wing.PuppetTargetList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PuppetTargetList_To_wing_PuppetTargetList(in, out, s)
}

func autoConvert_wing_PuppetTargetList_To_v1alpha1_PuppetTargetList(in *wing.PuppetTargetList, out *PuppetTargetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PuppetTarget)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_PuppetTargetList_To_v1alpha1_PuppetTargetList is an autogenerated conversion function.
func Convert_wing_PuppetTargetList_To_v1alpha1_PuppetTargetList(in *wing.PuppetTargetList, out *PuppetTargetList, s conversion.Scope) error {
	return autoConvert_wing_PuppetTargetList_To_v1alpha1_PuppetTargetList(in, out, s)
}

func autoConvert_v1alpha1_S3ManifestSource_To_wing_S3ManifestSource(in *S3ManifestSource, out *wing.S3ManifestSource, s conversion.Scope) error {
	out.BucketName = in.BucketName
	out.Path = in.Path
	out.Region = in.Region
	return nil
}

// Convert_v1alpha1_S3ManifestSource_To_wing_S3ManifestSource is an autogenerated conversion function.
func Convert_v1alpha1_S3ManifestSource_To_wing_S3ManifestSource(in *S3ManifestSource, out *wing.S3ManifestSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_S3ManifestSource_To_wing_S3ManifestSource(in, out, s)
}

func autoConvert_wing_S3ManifestSource_To_v1alpha1_S3ManifestSource(in *wing.S3ManifestSource, out *S3ManifestSource, s conversion.Scope) error {
	out.BucketName = in.BucketName
	out.Path = in.Path
	out.Region = in.Region
	return nil
}

// Convert_wing_S3ManifestSource_To_v1alpha1_S3ManifestSource is an autogenerated conversion function.
func Convert_wing_S3ManifestSource_To_v1alpha1_S3ManifestSource(in *wing.S3ManifestSource, out *S3ManifestSource, s conversion.Scope) error {
	return autoConvert_wing_S3ManifestSource_To_v1alpha1_S3ManifestSource(in, out, s)
}

func autoConvert_v1alpha1_WingJob_To_wing_WingJob(in *WingJob, out *wing.WingJob, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*wing.WingJobSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*wing.WingJobStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v1alpha1_WingJob_To_wing_WingJob is an autogenerated conversion function.
func Convert_v1alpha1_WingJob_To_wing_WingJob(in *WingJob, out *wing.WingJob, s conversion.Scope) error {
	return autoConvert_v1alpha1_WingJob_To_wing_WingJob(in, out, s)
}

func autoConvert_wing_WingJob_To_v1alpha1_WingJob(in *wing.WingJob, out *WingJob, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*WingJobSpec)(unsafe.Pointer(in.Spec))
	out.Status = (*WingJobStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_wing_WingJob_To_v1alpha1_WingJob is an autogenerated conversion function.
func Convert_wing_WingJob_To_v1alpha1_WingJob(in *wing.WingJob, out *WingJob, s conversion.Scope) error {
	return autoConvert_wing_WingJob_To_v1alpha1_WingJob(in, out, s)
}

func autoConvert_v1alpha1_WingJobList_To_wing_WingJobList(in *WingJobList, out *wing.WingJobList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.WingJob)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_WingJobList_To_wing_WingJobList is an autogenerated conversion function.
func Convert_v1alpha1_WingJobList_To_wing_WingJobList(in *WingJobList, out *wing.WingJobList, s conversion.Scope) error {
	return autoConvert_v1alpha1_WingJobList_To_wing_WingJobList(in, out, s)
}

func autoConvert_wing_WingJobList_To_v1alpha1_WingJobList(in *wing.WingJobList, out *WingJobList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]WingJob)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_WingJobList_To_v1alpha1_WingJobList is an autogenerated conversion function.
func Convert_wing_WingJobList_To_v1alpha1_WingJobList(in *wing.WingJobList, out *WingJobList, s conversion.Scope) error {
	return autoConvert_wing_WingJobList_To_v1alpha1_WingJobList(in, out, s)
}

func autoConvert_v1alpha1_WingJobSpec_To_wing_WingJobSpec(in *WingJobSpec, out *wing.WingJobSpec, s conversion.Scope) error {
	out.InstanceName = in.InstanceName
	out.PuppetTargetRef = in.PuppetTargetRef
	out.Operation = in.Operation
	out.RequestTimestamp = in.RequestTimestamp
	return nil
}

// Convert_v1alpha1_WingJobSpec_To_wing_WingJobSpec is an autogenerated conversion function.
func Convert_v1alpha1_WingJobSpec_To_wing_WingJobSpec(in *WingJobSpec, out *wing.WingJobSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_WingJobSpec_To_wing_WingJobSpec(in, out, s)
}

func autoConvert_wing_WingJobSpec_To_v1alpha1_WingJobSpec(in *wing.WingJobSpec, out *WingJobSpec, s conversion.Scope) error {
	out.InstanceName = in.InstanceName
	out.PuppetTargetRef = in.PuppetTargetRef
	out.Operation = in.Operation
	out.RequestTimestamp = in.RequestTimestamp
	return nil
}

// Convert_wing_WingJobSpec_To_v1alpha1_WingJobSpec is an autogenerated conversion function.
func Convert_wing_WingJobSpec_To_v1alpha1_WingJobSpec(in *wing.WingJobSpec, out *WingJobSpec, s conversion.Scope) error {
	return autoConvert_wing_WingJobSpec_To_v1alpha1_WingJobSpec(in, out, s)
}

func autoConvert_v1alpha1_WingJobStatus_To_wing_WingJobStatus(in *WingJobStatus, out *wing.WingJobStatus, s conversion.Scope) error {
	out.Messages = in.Messages
	out.ExitCode = in.ExitCode
	out.Completed = in.Completed
	out.LastUpdateTimestamp = in.LastUpdateTimestamp
	return nil
}

// Convert_v1alpha1_WingJobStatus_To_wing_WingJobStatus is an autogenerated conversion function.
func Convert_v1alpha1_WingJobStatus_To_wing_WingJobStatus(in *WingJobStatus, out *wing.WingJobStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WingJobStatus_To_wing_WingJobStatus(in, out, s)
}

func autoConvert_wing_WingJobStatus_To_v1alpha1_WingJobStatus(in *wing.WingJobStatus, out *WingJobStatus, s conversion.Scope) error {
	out.Messages = in.Messages
	out.ExitCode = in.ExitCode
	out.Completed = in.Completed
	out.LastUpdateTimestamp = in.LastUpdateTimestamp
	return nil
}

// Convert_wing_WingJobStatus_To_v1alpha1_WingJobStatus is an autogenerated conversion function.
func Convert_wing_WingJobStatus_To_v1alpha1_WingJobStatus(in *wing.WingJobStatus, out *WingJobStatus, s conversion.Scope) error {
	return autoConvert_wing_WingJobStatus_To_v1alpha1_WingJobStatus(in, out, s)
}
