/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	wing_v1alpha1 "github.com/jetstack/tarmak/pkg/apis/wing/v1alpha1"
	client "github.com/jetstack/tarmak/pkg/wing/client"
	internalinterfaces "github.com/jetstack/tarmak/pkg/wing/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jetstack/tarmak/pkg/wing/listers/wing/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// InstanceInformer provides access to a shared informer and lister for
// Instances.
type InstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.InstanceLister
}

type instanceInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewInstanceInformer constructs a new informer for Instance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInstanceInformer(client client.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.WingV1alpha1().Instances(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.WingV1alpha1().Instances(namespace).Watch(options)
			},
		},
		&wing_v1alpha1.Instance{},
		resyncPeriod,
		indexers,
	)
}

func defaultInstanceInformer(client client.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewInstanceInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *instanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&wing_v1alpha1.Instance{}, defaultInstanceInformer)
}

func (f *instanceInformer) Lister() v1alpha1.InstanceLister {
	return v1alpha1.NewInstanceLister(f.Informer().GetIndexer())
}
