// +build !ignore_autogenerated

// Copyright Jetstack Ltd. See LICENSE for details.

// This file was autogenerated by defaulter-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Cluster{}, func(obj interface{}) { SetObjectDefaults_Cluster(obj.(*Cluster)) })
	scheme.AddTypeDefaultingFunc(&ClusterList{}, func(obj interface{}) { SetObjectDefaults_ClusterList(obj.(*ClusterList)) })
	scheme.AddTypeDefaultingFunc(&InstancePool{}, func(obj interface{}) { SetObjectDefaults_InstancePool(obj.(*InstancePool)) })
	scheme.AddTypeDefaultingFunc(&Volume{}, func(obj interface{}) { SetObjectDefaults_Volume(obj.(*Volume)) })
	return nil
}

func SetObjectDefaults_Cluster(in *Cluster) {
	SetDefaults_Cluster(in)
	for i := range in.InstancePools {
		a := &in.InstancePools[i]
		SetObjectDefaults_InstancePool(a)
	}
	if in.Kubernetes != nil {
		if in.Kubernetes.ClusterAutoscaler != nil {
			SetDefaults_ClusterKubernetesClusterAutoscaler(in.Kubernetes.ClusterAutoscaler)
		}
		if in.Kubernetes.APIServer != nil {
			if in.Kubernetes.APIServer.Amazon != nil {
				if in.Kubernetes.APIServer.Amazon.PublicELBAccessLogs != nil {
					SetDefaults_ClusterKubernetesAPIServerAmazonAccessLogs(in.Kubernetes.APIServer.Amazon.PublicELBAccessLogs)
				}
				if in.Kubernetes.APIServer.Amazon.InternalELBAccessLogs != nil {
					SetDefaults_ClusterKubernetesAPIServerAmazonAccessLogs(in.Kubernetes.APIServer.Amazon.InternalELBAccessLogs)
				}
			}
		}
	}
}

func SetObjectDefaults_ClusterList(in *ClusterList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Cluster(a)
	}
}

func SetObjectDefaults_InstancePool(in *InstancePool) {
	SetDefaults_InstancePool(in)
	for i := range in.Volumes {
		a := &in.Volumes[i]
		SetObjectDefaults_Volume(a)
	}
}

func SetObjectDefaults_Volume(in *Volume) {
	SetDefaults_Volume(in)
}
