// Copyright Jetstack Ltd. See LICENSE for details.

// This package is generated by client-gen with custom arguments.

// This package has the automatically generated clientset.
package internalversion
