sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
matrix:
  include:
  - env: PUPPET_VERSION='~> 4.10.0' STRICT_VARIABLES=yes
  - env: PUPPET_VERSION='~> 5.3.0' STRICT_VARIABLES=yes
script: 'bundle exec rake test'
