#cloud-config
repo_update: true
repo_upgrade: all

preserve_hostname: true

users:
- default

- name: vault
  system: true
  home_dir: /var/lib/vault

write_files:
- path: /tmp/vault_server.yaml
  permissions: '0644'
  content: |
    ---
    vault_server::region: "${region}"
    vault_server::vault_tls_cert_path: "${vault_tls_cert_path}"
    vault_server::vault_tls_ca_path: "${vault_tls_ca_path}"
    vault_server::vault_tls_key_path: "${vault_tls_key_path}"
    vault_server::vault_unsealer_kms_key_id: "${vault_unsealer_kms_key_id}"
    vault_server::vault_unsealer_ssm_key_prefix: "${vault_unsealer_ssm_key_prefix}"

- path: /tmp/consul.yaml
  permissions: '0644'
  content: |
    ---
    consul::fqdn: "${fqdn}"
    consul::private_ip: "${private_ip}"
    consul::consul_master_token: "${consul_master_token}"
    consul::region: "${region}"
    consul::instance_count: "${instance_count}"
    consul::environment: "${environment}"
    consul::consul_encrypt: "${consul_encrypt}"
    consul::backup_bucket_prefix: "${backup_bucket_prefix}"
    consul::backup_schedule: "${backup_schedule}"
    consul::volume_id: "${volume_id}"
    consul::cloud_provider: "aws"

- path: /etc/systemd/system/puppet-download-manifests.service
  permissions: '0644'
  content: |
    [Unit]
    Description=Download puppet manifests
    Wants=network-online.target
    After=network.target network-online.target

    [Service]
    Environment=PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/opt/bin:/root/bin
    PermissionsStartOnly=true
    Restart=on-failure
    RestartSec=3
    ExecStart=/bin/sh -c 'set -e; aws s3 cp s3://${puppet_tar_gz_bucket_path} /tmp/puppet.tar.gz; mkdir -p /tmp/puppet-manifests; tar -xf /tmp/puppet.tar.gz -C /tmp/puppet-manifests/.; mkdir -p /tmp/puppet-manifests/modules/vault_server/hieradata; cp /tmp/vault_server.yaml /tmp/puppet-manifests/modules/vault_server/hieradata/vault_server.yaml; mkdir -p /tmp/puppet-manifests/modules/consul/hieradata; cp /tmp/consul.yaml /tmp/puppet-manifests/modules/consul/hieradata/consul.yaml'
    [Install]
    WantedBy=multi-user.target


- path: /etc/systemd/system/puppet-vault-init.service
  permissions: '0644'
  content: |
    [Unit]
    Description=Bootstrap vault using puppet
    Wants=network-online.target
    After=network.target network-online.target

    [Service]
    Environment=PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/opt/bin:/root/bin
    PermissionsStartOnly=true
    Restart=on-failure
    RestartSec=6
    SuccessExitStatus=0 2
    ExecStart=/opt/puppetlabs/bin/puppet apply --detailed-exitcodes --color no --environment production --modulepath /tmp/puppet-manifests/modules --hiera_config /tmp/puppet-manifests/modules/vault_server/hiera.yaml /tmp/puppet-manifests/modules/vault_server -e "include vault_server"
    [Install]
    WantedBy=multi-user.target

- path: /etc/systemd/system/puppet-consul-init.service
  permissions: '0644'
  content: |
    [Unit]
    Description=Bootstrap consul using puppet
    Wants=network-online.target
    After=network.target network-online.target

    [Service]
    Environment=PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/opt/bin:/root/bin
    PermissionsStartOnly=true
    Restart=on-failure
    RestartSec=6
    SuccessExitStatus=0 2
    ExecStart=/opt/puppetlabs/bin/puppet apply --detailed-exitcodes --color no --environment production --modulepath /tmp/puppet-manifests/modules --hiera_config /tmp/puppet-manifests/modules/consul/hiera.yaml /tmp/puppet-manifests/modules/consul -e "include consul"
    [Install]
    WantedBy=multi-user.target


runcmd:
- systemctl start puppet-download-manifests.service
- systemctl start puppet-vault-init.service
- systemctl start puppet-consul-init.service
