example_location: "examples"
api_groups:
  - "Tarmak"
  - "Wing"
  - "Cluster"
resource_categories:
- name: "Tarmak"
  include: "tarmak"
  resources:
  - name: "Config"
    version: "v1alpha1"
    group: "tarmak"
  - name: "Image"
    version: "v1alpha1"
    group: "tarmak"
  - name: "Flags"
    version: "v1alpha1"
    group: "tarmak"
  - name: "Cluster"
    version: "v1alpha1"
    group: "cluster"
  - name: "Machine"
    version: "v1alpha1"
    group: "wing"
  - name: "MachineSet"
    version: "v1alpha1"
    group: "wing"
  - name: "MachineDeployment"
    version: "v1alpha1"
    group: "wing"
