fixtures:
  symlinks:
    vault_server: "#{source_dir}"
    archive: "#{source_dir}/../archive"
    concat: "#{source_dir}/../concat"
    stdlib: "#{source_dir}/../stdlib"
    airworthy: "#{source_dir}/../airworthy"
    consul: "#{source_dir}/../consul"
