// Copyright Jetstack Ltd. See LICENSE for details.

// This file was automatically generated by lister-gen

package internalversion

// InstanceListerExpansion allows custom methods to be added to
// InstanceLister.
type InstanceListerExpansion interface{}

// InstanceNamespaceListerExpansion allows custom methods to be added to
// InstanceNamespaceLister.
type InstanceNamespaceListerExpansion interface{}
