// Copyright Jetstack Ltd. See LICENSE for details.

// This file was automatically generated by lister-gen

package internalversion

// MachineListerExpansion allows custom methods to be added to
// MachineLister.
type MachineListerExpansion interface{}

// MachineNamespaceListerExpansion allows custom methods to be added to
// MachineNamespaceLister.
type MachineNamespaceListerExpansion interface{}
