// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	tarmak "github.com/jetstack/tarmak/pkg/apis/tarmak"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_AWSConfig_To_tarmak_AWSConfig,
		Convert_tarmak_AWSConfig_To_v1alpha1_AWSConfig,
		Convert_v1alpha1_Config_To_tarmak_Config,
		Convert_tarmak_Config_To_v1alpha1_Config,
		Convert_v1alpha1_ConfigList_To_tarmak_ConfigList,
		Convert_tarmak_ConfigList_To_v1alpha1_ConfigList,
		Convert_v1alpha1_Context_To_tarmak_Context,
		Convert_tarmak_Context_To_v1alpha1_Context,
		Convert_v1alpha1_Environment_To_tarmak_Environment,
		Convert_tarmak_Environment_To_v1alpha1_Environment,
		Convert_v1alpha1_GCPConfig_To_tarmak_GCPConfig,
		Convert_tarmak_GCPConfig_To_v1alpha1_GCPConfig,
		Convert_v1alpha1_NodeGroup_To_tarmak_NodeGroup,
		Convert_tarmak_NodeGroup_To_v1alpha1_NodeGroup,
		Convert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS,
		Convert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS,
		Convert_v1alpha1_Stack_To_tarmak_Stack,
		Convert_tarmak_Stack_To_v1alpha1_Stack,
		Convert_v1alpha1_StackCustom_To_tarmak_StackCustom,
		Convert_tarmak_StackCustom_To_v1alpha1_StackCustom,
		Convert_v1alpha1_StackKubernetes_To_tarmak_StackKubernetes,
		Convert_tarmak_StackKubernetes_To_v1alpha1_StackKubernetes,
		Convert_v1alpha1_StackNetwork_To_tarmak_StackNetwork,
		Convert_tarmak_StackNetwork_To_v1alpha1_StackNetwork,
		Convert_v1alpha1_StackState_To_tarmak_StackState,
		Convert_tarmak_StackState_To_v1alpha1_StackState,
		Convert_v1alpha1_StackTools_To_tarmak_StackTools,
		Convert_tarmak_StackTools_To_v1alpha1_StackTools,
		Convert_v1alpha1_StackVault_To_tarmak_StackVault,
		Convert_tarmak_StackVault_To_v1alpha1_StackVault,
		Convert_v1alpha1_Volume_To_tarmak_Volume,
		Convert_tarmak_Volume_To_v1alpha1_Volume,
		Convert_v1alpha1_VolumeAWS_To_tarmak_VolumeAWS,
		Convert_tarmak_VolumeAWS_To_v1alpha1_VolumeAWS,
	)
}

func autoConvert_v1alpha1_AWSConfig_To_tarmak_AWSConfig(in *AWSConfig, out *tarmak.AWSConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.VaultPath = in.VaultPath
	out.AllowedAccountIDs = *(*[]string)(unsafe.Pointer(&in.AllowedAccountIDs))
	out.AvailabiltyZones = *(*[]string)(unsafe.Pointer(&in.AvailabiltyZones))
	out.Region = in.Region
	out.KeyName = in.KeyName
	return nil
}

// Convert_v1alpha1_AWSConfig_To_tarmak_AWSConfig is an autogenerated conversion function.
func Convert_v1alpha1_AWSConfig_To_tarmak_AWSConfig(in *AWSConfig, out *tarmak.AWSConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSConfig_To_tarmak_AWSConfig(in, out, s)
}

func autoConvert_tarmak_AWSConfig_To_v1alpha1_AWSConfig(in *tarmak.AWSConfig, out *AWSConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.VaultPath = in.VaultPath
	out.AllowedAccountIDs = *(*[]string)(unsafe.Pointer(&in.AllowedAccountIDs))
	out.AvailabiltyZones = *(*[]string)(unsafe.Pointer(&in.AvailabiltyZones))
	out.Region = in.Region
	out.KeyName = in.KeyName
	return nil
}

// Convert_tarmak_AWSConfig_To_v1alpha1_AWSConfig is an autogenerated conversion function.
func Convert_tarmak_AWSConfig_To_v1alpha1_AWSConfig(in *tarmak.AWSConfig, out *AWSConfig, s conversion.Scope) error {
	return autoConvert_tarmak_AWSConfig_To_v1alpha1_AWSConfig(in, out, s)
}

func autoConvert_v1alpha1_Config_To_tarmak_Config(in *Config, out *tarmak.Config, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.CurrentContext = in.CurrentContext
	out.Environments = *(*[]tarmak.Environment)(unsafe.Pointer(&in.Environments))
	out.Contact = in.Contact
	out.Project = in.Project
	return nil
}

// Convert_v1alpha1_Config_To_tarmak_Config is an autogenerated conversion function.
func Convert_v1alpha1_Config_To_tarmak_Config(in *Config, out *tarmak.Config, s conversion.Scope) error {
	return autoConvert_v1alpha1_Config_To_tarmak_Config(in, out, s)
}

func autoConvert_tarmak_Config_To_v1alpha1_Config(in *tarmak.Config, out *Config, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.CurrentContext = in.CurrentContext
	out.Environments = *(*[]Environment)(unsafe.Pointer(&in.Environments))
	out.Contact = in.Contact
	out.Project = in.Project
	return nil
}

// Convert_tarmak_Config_To_v1alpha1_Config is an autogenerated conversion function.
func Convert_tarmak_Config_To_v1alpha1_Config(in *tarmak.Config, out *Config, s conversion.Scope) error {
	return autoConvert_tarmak_Config_To_v1alpha1_Config(in, out, s)
}

func autoConvert_v1alpha1_ConfigList_To_tarmak_ConfigList(in *ConfigList, out *tarmak.ConfigList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Items = *(*[]tarmak.Config)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ConfigList_To_tarmak_ConfigList is an autogenerated conversion function.
func Convert_v1alpha1_ConfigList_To_tarmak_ConfigList(in *ConfigList, out *tarmak.ConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigList_To_tarmak_ConfigList(in, out, s)
}

func autoConvert_tarmak_ConfigList_To_v1alpha1_ConfigList(in *tarmak.ConfigList, out *ConfigList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if in.Items == nil {
		out.Items = make([]Config, 0)
	} else {
		out.Items = *(*[]Config)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_tarmak_ConfigList_To_v1alpha1_ConfigList is an autogenerated conversion function.
func Convert_tarmak_ConfigList_To_v1alpha1_ConfigList(in *tarmak.ConfigList, out *ConfigList, s conversion.Scope) error {
	return autoConvert_tarmak_ConfigList_To_v1alpha1_ConfigList(in, out, s)
}

func autoConvert_v1alpha1_Context_To_tarmak_Context(in *Context, out *tarmak.Context, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Stacks = *(*[]tarmak.Stack)(unsafe.Pointer(&in.Stacks))
	out.Contact = in.Contact
	out.Project = in.Project
	out.BaseImage = in.BaseImage
	return nil
}

// Convert_v1alpha1_Context_To_tarmak_Context is an autogenerated conversion function.
func Convert_v1alpha1_Context_To_tarmak_Context(in *Context, out *tarmak.Context, s conversion.Scope) error {
	return autoConvert_v1alpha1_Context_To_tarmak_Context(in, out, s)
}

func autoConvert_tarmak_Context_To_v1alpha1_Context(in *tarmak.Context, out *Context, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Stacks = *(*[]Stack)(unsafe.Pointer(&in.Stacks))
	out.Contact = in.Contact
	out.Project = in.Project
	out.BaseImage = in.BaseImage
	return nil
}

// Convert_tarmak_Context_To_v1alpha1_Context is an autogenerated conversion function.
func Convert_tarmak_Context_To_v1alpha1_Context(in *tarmak.Context, out *Context, s conversion.Scope) error {
	return autoConvert_tarmak_Context_To_v1alpha1_Context(in, out, s)
}

func autoConvert_v1alpha1_Environment_To_tarmak_Environment(in *Environment, out *tarmak.Environment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.AWS = (*tarmak.AWSConfig)(unsafe.Pointer(in.AWS))
	out.GCP = (*tarmak.GCPConfig)(unsafe.Pointer(in.GCP))
	out.Contact = in.Contact
	out.Project = in.Project
	out.SSHKeyPath = in.SSHKeyPath
	out.Contexts = *(*[]tarmak.Context)(unsafe.Pointer(&in.Contexts))
	return nil
}

// Convert_v1alpha1_Environment_To_tarmak_Environment is an autogenerated conversion function.
func Convert_v1alpha1_Environment_To_tarmak_Environment(in *Environment, out *tarmak.Environment, s conversion.Scope) error {
	return autoConvert_v1alpha1_Environment_To_tarmak_Environment(in, out, s)
}

func autoConvert_tarmak_Environment_To_v1alpha1_Environment(in *tarmak.Environment, out *Environment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.AWS = (*AWSConfig)(unsafe.Pointer(in.AWS))
	out.GCP = (*GCPConfig)(unsafe.Pointer(in.GCP))
	out.Contact = in.Contact
	out.Project = in.Project
	out.SSHKeyPath = in.SSHKeyPath
	out.Contexts = *(*[]Context)(unsafe.Pointer(&in.Contexts))
	return nil
}

// Convert_tarmak_Environment_To_v1alpha1_Environment is an autogenerated conversion function.
func Convert_tarmak_Environment_To_v1alpha1_Environment(in *tarmak.Environment, out *Environment, s conversion.Scope) error {
	return autoConvert_tarmak_Environment_To_v1alpha1_Environment(in, out, s)
}

func autoConvert_v1alpha1_GCPConfig_To_tarmak_GCPConfig(in *GCPConfig, out *tarmak.GCPConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Zones = *(*[]string)(unsafe.Pointer(&in.Zones))
	out.Region = in.Region
	out.Project = in.Project
	return nil
}

// Convert_v1alpha1_GCPConfig_To_tarmak_GCPConfig is an autogenerated conversion function.
func Convert_v1alpha1_GCPConfig_To_tarmak_GCPConfig(in *GCPConfig, out *tarmak.GCPConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_GCPConfig_To_tarmak_GCPConfig(in, out, s)
}

func autoConvert_tarmak_GCPConfig_To_v1alpha1_GCPConfig(in *tarmak.GCPConfig, out *GCPConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Zones = *(*[]string)(unsafe.Pointer(&in.Zones))
	out.Region = in.Region
	out.Project = in.Project
	return nil
}

// Convert_tarmak_GCPConfig_To_v1alpha1_GCPConfig is an autogenerated conversion function.
func Convert_tarmak_GCPConfig_To_v1alpha1_GCPConfig(in *tarmak.GCPConfig, out *GCPConfig, s conversion.Scope) error {
	return autoConvert_tarmak_GCPConfig_To_v1alpha1_GCPConfig(in, out, s)
}

func autoConvert_v1alpha1_NodeGroup_To_tarmak_NodeGroup(in *NodeGroup, out *tarmak.NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Role = in.Role
	out.Count = in.Count
	out.Volumes = *(*[]tarmak.Volume)(unsafe.Pointer(&in.Volumes))
	out.AWS = (*tarmak.NodeGroupAWS)(unsafe.Pointer(in.AWS))
	return nil
}

// Convert_v1alpha1_NodeGroup_To_tarmak_NodeGroup is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroup_To_tarmak_NodeGroup(in *NodeGroup, out *tarmak.NodeGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroup_To_tarmak_NodeGroup(in, out, s)
}

func autoConvert_tarmak_NodeGroup_To_v1alpha1_NodeGroup(in *tarmak.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Role = in.Role
	out.Count = in.Count
	out.Volumes = *(*[]Volume)(unsafe.Pointer(&in.Volumes))
	out.AWS = (*NodeGroupAWS)(unsafe.Pointer(in.AWS))
	return nil
}

// Convert_tarmak_NodeGroup_To_v1alpha1_NodeGroup is an autogenerated conversion function.
func Convert_tarmak_NodeGroup_To_v1alpha1_NodeGroup(in *tarmak.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	return autoConvert_tarmak_NodeGroup_To_v1alpha1_NodeGroup(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS(in *NodeGroupAWS, out *tarmak.NodeGroupAWS, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	out.SpotPrice = in.SpotPrice
	return nil
}

// Convert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS(in *NodeGroupAWS, out *tarmak.NodeGroupAWS, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS(in, out, s)
}

func autoConvert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS(in *tarmak.NodeGroupAWS, out *NodeGroupAWS, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	out.SpotPrice = in.SpotPrice
	return nil
}

// Convert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS is an autogenerated conversion function.
func Convert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS(in *tarmak.NodeGroupAWS, out *NodeGroupAWS, s conversion.Scope) error {
	return autoConvert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS(in, out, s)
}

func autoConvert_v1alpha1_Stack_To_tarmak_Stack(in *Stack, out *tarmak.Stack, s conversion.Scope) error {
	out.State = (*tarmak.StackState)(unsafe.Pointer(in.State))
	out.Network = (*tarmak.StackNetwork)(unsafe.Pointer(in.Network))
	out.Tools = (*tarmak.StackTools)(unsafe.Pointer(in.Tools))
	out.Vault = (*tarmak.StackVault)(unsafe.Pointer(in.Vault))
	out.Kubernetes = (*tarmak.StackKubernetes)(unsafe.Pointer(in.Kubernetes))
	out.Custom = (*tarmak.StackCustom)(unsafe.Pointer(in.Custom))
	out.NodeGroups = *(*[]tarmak.NodeGroup)(unsafe.Pointer(&in.NodeGroups))
	return nil
}

// Convert_v1alpha1_Stack_To_tarmak_Stack is an autogenerated conversion function.
func Convert_v1alpha1_Stack_To_tarmak_Stack(in *Stack, out *tarmak.Stack, s conversion.Scope) error {
	return autoConvert_v1alpha1_Stack_To_tarmak_Stack(in, out, s)
}

func autoConvert_tarmak_Stack_To_v1alpha1_Stack(in *tarmak.Stack, out *Stack, s conversion.Scope) error {
	out.State = (*StackState)(unsafe.Pointer(in.State))
	out.Network = (*StackNetwork)(unsafe.Pointer(in.Network))
	out.Tools = (*StackTools)(unsafe.Pointer(in.Tools))
	out.Vault = (*StackVault)(unsafe.Pointer(in.Vault))
	out.Kubernetes = (*StackKubernetes)(unsafe.Pointer(in.Kubernetes))
	out.Custom = (*StackCustom)(unsafe.Pointer(in.Custom))
	out.NodeGroups = *(*[]NodeGroup)(unsafe.Pointer(&in.NodeGroups))
	return nil
}

// Convert_tarmak_Stack_To_v1alpha1_Stack is an autogenerated conversion function.
func Convert_tarmak_Stack_To_v1alpha1_Stack(in *tarmak.Stack, out *Stack, s conversion.Scope) error {
	return autoConvert_tarmak_Stack_To_v1alpha1_Stack(in, out, s)
}

func autoConvert_v1alpha1_StackCustom_To_tarmak_StackCustom(in *StackCustom, out *tarmak.StackCustom, s conversion.Scope) error {
	out.Name = in.Name
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_StackCustom_To_tarmak_StackCustom is an autogenerated conversion function.
func Convert_v1alpha1_StackCustom_To_tarmak_StackCustom(in *StackCustom, out *tarmak.StackCustom, s conversion.Scope) error {
	return autoConvert_v1alpha1_StackCustom_To_tarmak_StackCustom(in, out, s)
}

func autoConvert_tarmak_StackCustom_To_v1alpha1_StackCustom(in *tarmak.StackCustom, out *StackCustom, s conversion.Scope) error {
	out.Name = in.Name
	out.Path = in.Path
	return nil
}

// Convert_tarmak_StackCustom_To_v1alpha1_StackCustom is an autogenerated conversion function.
func Convert_tarmak_StackCustom_To_v1alpha1_StackCustom(in *tarmak.StackCustom, out *StackCustom, s conversion.Scope) error {
	return autoConvert_tarmak_StackCustom_To_v1alpha1_StackCustom(in, out, s)
}

func autoConvert_v1alpha1_StackKubernetes_To_tarmak_StackKubernetes(in *StackKubernetes, out *tarmak.StackKubernetes, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_StackKubernetes_To_tarmak_StackKubernetes is an autogenerated conversion function.
func Convert_v1alpha1_StackKubernetes_To_tarmak_StackKubernetes(in *StackKubernetes, out *tarmak.StackKubernetes, s conversion.Scope) error {
	return autoConvert_v1alpha1_StackKubernetes_To_tarmak_StackKubernetes(in, out, s)
}

func autoConvert_tarmak_StackKubernetes_To_v1alpha1_StackKubernetes(in *tarmak.StackKubernetes, out *StackKubernetes, s conversion.Scope) error {
	return nil
}

// Convert_tarmak_StackKubernetes_To_v1alpha1_StackKubernetes is an autogenerated conversion function.
func Convert_tarmak_StackKubernetes_To_v1alpha1_StackKubernetes(in *tarmak.StackKubernetes, out *StackKubernetes, s conversion.Scope) error {
	return autoConvert_tarmak_StackKubernetes_To_v1alpha1_StackKubernetes(in, out, s)
}

func autoConvert_v1alpha1_StackNetwork_To_tarmak_StackNetwork(in *StackNetwork, out *tarmak.StackNetwork, s conversion.Scope) error {
	out.PeerContext = in.PeerContext
	out.NetworkCIDR = in.NetworkCIDR
	out.PrivateZone = in.PrivateZone
	return nil
}

// Convert_v1alpha1_StackNetwork_To_tarmak_StackNetwork is an autogenerated conversion function.
func Convert_v1alpha1_StackNetwork_To_tarmak_StackNetwork(in *StackNetwork, out *tarmak.StackNetwork, s conversion.Scope) error {
	return autoConvert_v1alpha1_StackNetwork_To_tarmak_StackNetwork(in, out, s)
}

func autoConvert_tarmak_StackNetwork_To_v1alpha1_StackNetwork(in *tarmak.StackNetwork, out *StackNetwork, s conversion.Scope) error {
	out.PeerContext = in.PeerContext
	out.NetworkCIDR = in.NetworkCIDR
	out.PrivateZone = in.PrivateZone
	return nil
}

// Convert_tarmak_StackNetwork_To_v1alpha1_StackNetwork is an autogenerated conversion function.
func Convert_tarmak_StackNetwork_To_v1alpha1_StackNetwork(in *tarmak.StackNetwork, out *StackNetwork, s conversion.Scope) error {
	return autoConvert_tarmak_StackNetwork_To_v1alpha1_StackNetwork(in, out, s)
}

func autoConvert_v1alpha1_StackState_To_tarmak_StackState(in *StackState, out *tarmak.StackState, s conversion.Scope) error {
	out.BucketPrefix = in.BucketPrefix
	out.PublicZone = in.PublicZone
	return nil
}

// Convert_v1alpha1_StackState_To_tarmak_StackState is an autogenerated conversion function.
func Convert_v1alpha1_StackState_To_tarmak_StackState(in *StackState, out *tarmak.StackState, s conversion.Scope) error {
	return autoConvert_v1alpha1_StackState_To_tarmak_StackState(in, out, s)
}

func autoConvert_tarmak_StackState_To_v1alpha1_StackState(in *tarmak.StackState, out *StackState, s conversion.Scope) error {
	out.BucketPrefix = in.BucketPrefix
	out.PublicZone = in.PublicZone
	return nil
}

// Convert_tarmak_StackState_To_v1alpha1_StackState is an autogenerated conversion function.
func Convert_tarmak_StackState_To_v1alpha1_StackState(in *tarmak.StackState, out *StackState, s conversion.Scope) error {
	return autoConvert_tarmak_StackState_To_v1alpha1_StackState(in, out, s)
}

func autoConvert_v1alpha1_StackTools_To_tarmak_StackTools(in *StackTools, out *tarmak.StackTools, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_StackTools_To_tarmak_StackTools is an autogenerated conversion function.
func Convert_v1alpha1_StackTools_To_tarmak_StackTools(in *StackTools, out *tarmak.StackTools, s conversion.Scope) error {
	return autoConvert_v1alpha1_StackTools_To_tarmak_StackTools(in, out, s)
}

func autoConvert_tarmak_StackTools_To_v1alpha1_StackTools(in *tarmak.StackTools, out *StackTools, s conversion.Scope) error {
	return nil
}

// Convert_tarmak_StackTools_To_v1alpha1_StackTools is an autogenerated conversion function.
func Convert_tarmak_StackTools_To_v1alpha1_StackTools(in *tarmak.StackTools, out *StackTools, s conversion.Scope) error {
	return autoConvert_tarmak_StackTools_To_v1alpha1_StackTools(in, out, s)
}

func autoConvert_v1alpha1_StackVault_To_tarmak_StackVault(in *StackVault, out *tarmak.StackVault, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_StackVault_To_tarmak_StackVault is an autogenerated conversion function.
func Convert_v1alpha1_StackVault_To_tarmak_StackVault(in *StackVault, out *tarmak.StackVault, s conversion.Scope) error {
	return autoConvert_v1alpha1_StackVault_To_tarmak_StackVault(in, out, s)
}

func autoConvert_tarmak_StackVault_To_v1alpha1_StackVault(in *tarmak.StackVault, out *StackVault, s conversion.Scope) error {
	return nil
}

// Convert_tarmak_StackVault_To_v1alpha1_StackVault is an autogenerated conversion function.
func Convert_tarmak_StackVault_To_v1alpha1_StackVault(in *tarmak.StackVault, out *StackVault, s conversion.Scope) error {
	return autoConvert_tarmak_StackVault_To_v1alpha1_StackVault(in, out, s)
}

func autoConvert_v1alpha1_Volume_To_tarmak_Volume(in *Volume, out *tarmak.Volume, s conversion.Scope) error {
	out.Name = in.Name
	out.Size = in.Size
	out.AWS = (*tarmak.VolumeAWS)(unsafe.Pointer(in.AWS))
	return nil
}

// Convert_v1alpha1_Volume_To_tarmak_Volume is an autogenerated conversion function.
func Convert_v1alpha1_Volume_To_tarmak_Volume(in *Volume, out *tarmak.Volume, s conversion.Scope) error {
	return autoConvert_v1alpha1_Volume_To_tarmak_Volume(in, out, s)
}

func autoConvert_tarmak_Volume_To_v1alpha1_Volume(in *tarmak.Volume, out *Volume, s conversion.Scope) error {
	out.Name = in.Name
	out.Size = in.Size
	out.AWS = (*VolumeAWS)(unsafe.Pointer(in.AWS))
	return nil
}

// Convert_tarmak_Volume_To_v1alpha1_Volume is an autogenerated conversion function.
func Convert_tarmak_Volume_To_v1alpha1_Volume(in *tarmak.Volume, out *Volume, s conversion.Scope) error {
	return autoConvert_tarmak_Volume_To_v1alpha1_Volume(in, out, s)
}

func autoConvert_v1alpha1_VolumeAWS_To_tarmak_VolumeAWS(in *VolumeAWS, out *tarmak.VolumeAWS, s conversion.Scope) error {
	out.Type = in.Type
	return nil
}

// Convert_v1alpha1_VolumeAWS_To_tarmak_VolumeAWS is an autogenerated conversion function.
func Convert_v1alpha1_VolumeAWS_To_tarmak_VolumeAWS(in *VolumeAWS, out *tarmak.VolumeAWS, s conversion.Scope) error {
	return autoConvert_v1alpha1_VolumeAWS_To_tarmak_VolumeAWS(in, out, s)
}

func autoConvert_tarmak_VolumeAWS_To_v1alpha1_VolumeAWS(in *tarmak.VolumeAWS, out *VolumeAWS, s conversion.Scope) error {
	out.Type = in.Type
	return nil
}

// Convert_tarmak_VolumeAWS_To_v1alpha1_VolumeAWS is an autogenerated conversion function.
func Convert_tarmak_VolumeAWS_To_v1alpha1_VolumeAWS(in *tarmak.VolumeAWS, out *VolumeAWS, s conversion.Scope) error {
	return autoConvert_tarmak_VolumeAWS_To_v1alpha1_VolumeAWS(in, out, s)
}
