// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	tarmak "github.com/jetstack/tarmak/pkg/apis/tarmak"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_BaseParams_To_tarmak_BaseParams,
		Convert_tarmak_BaseParams_To_v1alpha1_BaseParams,
		Convert_v1alpha1_Context_To_tarmak_Context,
		Convert_tarmak_Context_To_v1alpha1_Context,
		Convert_v1alpha1_ContextList_To_tarmak_ContextList,
		Convert_tarmak_ContextList_To_v1alpha1_ContextList,
		Convert_v1alpha1_ContextSpec_To_tarmak_ContextSpec,
		Convert_tarmak_ContextSpec_To_v1alpha1_ContextSpec,
		Convert_v1alpha1_ContextStatus_To_tarmak_ContextStatus,
		Convert_tarmak_ContextStatus_To_v1alpha1_ContextStatus,
		Convert_v1alpha1_Environment_To_tarmak_Environment,
		Convert_tarmak_Environment_To_v1alpha1_Environment,
		Convert_v1alpha1_EnvironmentList_To_tarmak_EnvironmentList,
		Convert_tarmak_EnvironmentList_To_v1alpha1_EnvironmentList,
		Convert_v1alpha1_NodeGroup_To_tarmak_NodeGroup,
		Convert_tarmak_NodeGroup_To_v1alpha1_NodeGroup,
		Convert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS,
		Convert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS,
		Convert_v1alpha1_NodeGroupDisk_To_tarmak_NodeGroupDisk,
		Convert_tarmak_NodeGroupDisk_To_v1alpha1_NodeGroupDisk,
		Convert_v1alpha1_NodeGroupTypeOrderedInstances_To_tarmak_NodeGroupTypeOrderedInstances,
		Convert_tarmak_NodeGroupTypeOrderedInstances_To_v1alpha1_NodeGroupTypeOrderedInstances,
		Convert_v1alpha1_NodeGroupTypeScalingGroup_To_tarmak_NodeGroupTypeScalingGroup,
		Convert_tarmak_NodeGroupTypeScalingGroup_To_v1alpha1_NodeGroupTypeScalingGroup,
	)
}

func autoConvert_v1alpha1_BaseParams_To_tarmak_BaseParams(in *BaseParams, out *tarmak.BaseParams, s conversion.Scope) error {
	out.Contact = in.Contact
	out.Project = in.Project
	out.TrustedIPRange = *(*[]string)(unsafe.Pointer(&in.TrustedIPRange))
	return nil
}

// Convert_v1alpha1_BaseParams_To_tarmak_BaseParams is an autogenerated conversion function.
func Convert_v1alpha1_BaseParams_To_tarmak_BaseParams(in *BaseParams, out *tarmak.BaseParams, s conversion.Scope) error {
	return autoConvert_v1alpha1_BaseParams_To_tarmak_BaseParams(in, out, s)
}

func autoConvert_tarmak_BaseParams_To_v1alpha1_BaseParams(in *tarmak.BaseParams, out *BaseParams, s conversion.Scope) error {
	out.Contact = in.Contact
	out.Project = in.Project
	out.TrustedIPRange = *(*[]string)(unsafe.Pointer(&in.TrustedIPRange))
	return nil
}

// Convert_tarmak_BaseParams_To_v1alpha1_BaseParams is an autogenerated conversion function.
func Convert_tarmak_BaseParams_To_v1alpha1_BaseParams(in *tarmak.BaseParams, out *BaseParams, s conversion.Scope) error {
	return autoConvert_tarmak_BaseParams_To_v1alpha1_BaseParams(in, out, s)
}

func autoConvert_v1alpha1_Context_To_tarmak_Context(in *Context, out *tarmak.Context, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ContextSpec_To_tarmak_ContextSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContextStatus_To_tarmak_ContextStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Context_To_tarmak_Context is an autogenerated conversion function.
func Convert_v1alpha1_Context_To_tarmak_Context(in *Context, out *tarmak.Context, s conversion.Scope) error {
	return autoConvert_v1alpha1_Context_To_tarmak_Context(in, out, s)
}

func autoConvert_tarmak_Context_To_v1alpha1_Context(in *tarmak.Context, out *Context, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_tarmak_ContextSpec_To_v1alpha1_ContextSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_tarmak_ContextStatus_To_v1alpha1_ContextStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_tarmak_Context_To_v1alpha1_Context is an autogenerated conversion function.
func Convert_tarmak_Context_To_v1alpha1_Context(in *tarmak.Context, out *Context, s conversion.Scope) error {
	return autoConvert_tarmak_Context_To_v1alpha1_Context(in, out, s)
}

func autoConvert_v1alpha1_ContextList_To_tarmak_ContextList(in *ContextList, out *tarmak.ContextList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if err := Convert_v1alpha1_BaseParams_To_tarmak_BaseParams(&in.BaseParams, &out.BaseParams, s); err != nil {
		return err
	}
	out.Items = *(*[]tarmak.Context)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ContextList_To_tarmak_ContextList is an autogenerated conversion function.
func Convert_v1alpha1_ContextList_To_tarmak_ContextList(in *ContextList, out *tarmak.ContextList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContextList_To_tarmak_ContextList(in, out, s)
}

func autoConvert_tarmak_ContextList_To_v1alpha1_ContextList(in *tarmak.ContextList, out *ContextList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if err := Convert_tarmak_BaseParams_To_v1alpha1_BaseParams(&in.BaseParams, &out.BaseParams, s); err != nil {
		return err
	}
	out.Items = *(*[]Context)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_tarmak_ContextList_To_v1alpha1_ContextList is an autogenerated conversion function.
func Convert_tarmak_ContextList_To_v1alpha1_ContextList(in *tarmak.ContextList, out *ContextList, s conversion.Scope) error {
	return autoConvert_tarmak_ContextList_To_v1alpha1_ContextList(in, out, s)
}

func autoConvert_v1alpha1_ContextSpec_To_tarmak_ContextSpec(in *ContextSpec, out *tarmak.ContextSpec, s conversion.Scope) error {
	out.NodeGroups = *(*[]tarmak.NodeGroup)(unsafe.Pointer(&in.NodeGroups))
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_ContextSpec_To_tarmak_ContextSpec is an autogenerated conversion function.
func Convert_v1alpha1_ContextSpec_To_tarmak_ContextSpec(in *ContextSpec, out *tarmak.ContextSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContextSpec_To_tarmak_ContextSpec(in, out, s)
}

func autoConvert_tarmak_ContextSpec_To_v1alpha1_ContextSpec(in *tarmak.ContextSpec, out *ContextSpec, s conversion.Scope) error {
	out.NodeGroups = *(*[]NodeGroup)(unsafe.Pointer(&in.NodeGroups))
	out.Version = in.Version
	return nil
}

// Convert_tarmak_ContextSpec_To_v1alpha1_ContextSpec is an autogenerated conversion function.
func Convert_tarmak_ContextSpec_To_v1alpha1_ContextSpec(in *tarmak.ContextSpec, out *ContextSpec, s conversion.Scope) error {
	return autoConvert_tarmak_ContextSpec_To_v1alpha1_ContextSpec(in, out, s)
}

func autoConvert_v1alpha1_ContextStatus_To_tarmak_ContextStatus(in *ContextStatus, out *tarmak.ContextStatus, s conversion.Scope) error {
	out.Fine = in.Fine
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_ContextStatus_To_tarmak_ContextStatus is an autogenerated conversion function.
func Convert_v1alpha1_ContextStatus_To_tarmak_ContextStatus(in *ContextStatus, out *tarmak.ContextStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContextStatus_To_tarmak_ContextStatus(in, out, s)
}

func autoConvert_tarmak_ContextStatus_To_v1alpha1_ContextStatus(in *tarmak.ContextStatus, out *ContextStatus, s conversion.Scope) error {
	out.Fine = in.Fine
	out.Version = in.Version
	return nil
}

// Convert_tarmak_ContextStatus_To_v1alpha1_ContextStatus is an autogenerated conversion function.
func Convert_tarmak_ContextStatus_To_v1alpha1_ContextStatus(in *tarmak.ContextStatus, out *ContextStatus, s conversion.Scope) error {
	return autoConvert_tarmak_ContextStatus_To_v1alpha1_ContextStatus(in, out, s)
}

func autoConvert_v1alpha1_Environment_To_tarmak_Environment(in *Environment, out *tarmak.Environment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BaseParams_To_tarmak_BaseParams(&in.BaseParams, &out.BaseParams, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContextSpec_To_tarmak_ContextSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContextStatus_To_tarmak_ContextStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Environment_To_tarmak_Environment is an autogenerated conversion function.
func Convert_v1alpha1_Environment_To_tarmak_Environment(in *Environment, out *tarmak.Environment, s conversion.Scope) error {
	return autoConvert_v1alpha1_Environment_To_tarmak_Environment(in, out, s)
}

func autoConvert_tarmak_Environment_To_v1alpha1_Environment(in *tarmak.Environment, out *Environment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_tarmak_BaseParams_To_v1alpha1_BaseParams(&in.BaseParams, &out.BaseParams, s); err != nil {
		return err
	}
	if err := Convert_tarmak_ContextSpec_To_v1alpha1_ContextSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_tarmak_ContextStatus_To_v1alpha1_ContextStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_tarmak_Environment_To_v1alpha1_Environment is an autogenerated conversion function.
func Convert_tarmak_Environment_To_v1alpha1_Environment(in *tarmak.Environment, out *Environment, s conversion.Scope) error {
	return autoConvert_tarmak_Environment_To_v1alpha1_Environment(in, out, s)
}

func autoConvert_v1alpha1_EnvironmentList_To_tarmak_EnvironmentList(in *EnvironmentList, out *tarmak.EnvironmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]tarmak.Environment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_EnvironmentList_To_tarmak_EnvironmentList is an autogenerated conversion function.
func Convert_v1alpha1_EnvironmentList_To_tarmak_EnvironmentList(in *EnvironmentList, out *tarmak.EnvironmentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_EnvironmentList_To_tarmak_EnvironmentList(in, out, s)
}

func autoConvert_tarmak_EnvironmentList_To_v1alpha1_EnvironmentList(in *tarmak.EnvironmentList, out *EnvironmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Environment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_tarmak_EnvironmentList_To_v1alpha1_EnvironmentList is an autogenerated conversion function.
func Convert_tarmak_EnvironmentList_To_v1alpha1_EnvironmentList(in *tarmak.EnvironmentList, out *EnvironmentList, s conversion.Scope) error {
	return autoConvert_tarmak_EnvironmentList_To_v1alpha1_EnvironmentList(in, out, s)
}

func autoConvert_v1alpha1_NodeGroup_To_tarmak_NodeGroup(in *NodeGroup, out *tarmak.NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.RootDiskSize = in.RootDiskSize
	out.NodeGroupDisk = *(*[]tarmak.NodeGroupDisk)(unsafe.Pointer(&in.NodeGroupDisk))
	out.Role = in.Role
	return nil
}

// Convert_v1alpha1_NodeGroup_To_tarmak_NodeGroup is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroup_To_tarmak_NodeGroup(in *NodeGroup, out *tarmak.NodeGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroup_To_tarmak_NodeGroup(in, out, s)
}

func autoConvert_tarmak_NodeGroup_To_v1alpha1_NodeGroup(in *tarmak.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.RootDiskSize = in.RootDiskSize
	out.NodeGroupDisk = *(*[]NodeGroupDisk)(unsafe.Pointer(&in.NodeGroupDisk))
	out.Role = in.Role
	return nil
}

// Convert_tarmak_NodeGroup_To_v1alpha1_NodeGroup is an autogenerated conversion function.
func Convert_tarmak_NodeGroup_To_v1alpha1_NodeGroup(in *tarmak.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	return autoConvert_tarmak_NodeGroup_To_v1alpha1_NodeGroup(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS(in *NodeGroupAWS, out *tarmak.NodeGroupAWS, s conversion.Scope) error {
	out.AdditionalIAMPolicy = in.AdditionalIAMPolicy
	out.SpotPrice = in.SpotPrice
	out.InstanceType = in.InstanceType
	return nil
}

// Convert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS(in *NodeGroupAWS, out *tarmak.NodeGroupAWS, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupAWS_To_tarmak_NodeGroupAWS(in, out, s)
}

func autoConvert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS(in *tarmak.NodeGroupAWS, out *NodeGroupAWS, s conversion.Scope) error {
	out.AdditionalIAMPolicy = in.AdditionalIAMPolicy
	out.SpotPrice = in.SpotPrice
	out.InstanceType = in.InstanceType
	return nil
}

// Convert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS is an autogenerated conversion function.
func Convert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS(in *tarmak.NodeGroupAWS, out *NodeGroupAWS, s conversion.Scope) error {
	return autoConvert_tarmak_NodeGroupAWS_To_v1alpha1_NodeGroupAWS(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupDisk_To_tarmak_NodeGroupDisk(in *NodeGroupDisk, out *tarmak.NodeGroupDisk, s conversion.Scope) error {
	out.Name = in.Name
	out.DiskSize = in.DiskSize
	return nil
}

// Convert_v1alpha1_NodeGroupDisk_To_tarmak_NodeGroupDisk is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupDisk_To_tarmak_NodeGroupDisk(in *NodeGroupDisk, out *tarmak.NodeGroupDisk, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupDisk_To_tarmak_NodeGroupDisk(in, out, s)
}

func autoConvert_tarmak_NodeGroupDisk_To_v1alpha1_NodeGroupDisk(in *tarmak.NodeGroupDisk, out *NodeGroupDisk, s conversion.Scope) error {
	out.Name = in.Name
	out.DiskSize = in.DiskSize
	return nil
}

// Convert_tarmak_NodeGroupDisk_To_v1alpha1_NodeGroupDisk is an autogenerated conversion function.
func Convert_tarmak_NodeGroupDisk_To_v1alpha1_NodeGroupDisk(in *tarmak.NodeGroupDisk, out *NodeGroupDisk, s conversion.Scope) error {
	return autoConvert_tarmak_NodeGroupDisk_To_v1alpha1_NodeGroupDisk(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupTypeOrderedInstances_To_tarmak_NodeGroupTypeOrderedInstances(in *NodeGroupTypeOrderedInstances, out *tarmak.NodeGroupTypeOrderedInstances, s conversion.Scope) error {
	out.Count = in.Count
	return nil
}

// Convert_v1alpha1_NodeGroupTypeOrderedInstances_To_tarmak_NodeGroupTypeOrderedInstances is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupTypeOrderedInstances_To_tarmak_NodeGroupTypeOrderedInstances(in *NodeGroupTypeOrderedInstances, out *tarmak.NodeGroupTypeOrderedInstances, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupTypeOrderedInstances_To_tarmak_NodeGroupTypeOrderedInstances(in, out, s)
}

func autoConvert_tarmak_NodeGroupTypeOrderedInstances_To_v1alpha1_NodeGroupTypeOrderedInstances(in *tarmak.NodeGroupTypeOrderedInstances, out *NodeGroupTypeOrderedInstances, s conversion.Scope) error {
	out.Count = in.Count
	return nil
}

// Convert_tarmak_NodeGroupTypeOrderedInstances_To_v1alpha1_NodeGroupTypeOrderedInstances is an autogenerated conversion function.
func Convert_tarmak_NodeGroupTypeOrderedInstances_To_v1alpha1_NodeGroupTypeOrderedInstances(in *tarmak.NodeGroupTypeOrderedInstances, out *NodeGroupTypeOrderedInstances, s conversion.Scope) error {
	return autoConvert_tarmak_NodeGroupTypeOrderedInstances_To_v1alpha1_NodeGroupTypeOrderedInstances(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupTypeScalingGroup_To_tarmak_NodeGroupTypeScalingGroup(in *NodeGroupTypeScalingGroup, out *tarmak.NodeGroupTypeScalingGroup, s conversion.Scope) error {
	out.MinCount = in.MinCount
	out.MaxCount = in.MaxCount
	out.DesiredCount = in.DesiredCount
	return nil
}

// Convert_v1alpha1_NodeGroupTypeScalingGroup_To_tarmak_NodeGroupTypeScalingGroup is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupTypeScalingGroup_To_tarmak_NodeGroupTypeScalingGroup(in *NodeGroupTypeScalingGroup, out *tarmak.NodeGroupTypeScalingGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupTypeScalingGroup_To_tarmak_NodeGroupTypeScalingGroup(in, out, s)
}

func autoConvert_tarmak_NodeGroupTypeScalingGroup_To_v1alpha1_NodeGroupTypeScalingGroup(in *tarmak.NodeGroupTypeScalingGroup, out *NodeGroupTypeScalingGroup, s conversion.Scope) error {
	out.MinCount = in.MinCount
	out.MaxCount = in.MaxCount
	out.DesiredCount = in.DesiredCount
	return nil
}

// Convert_tarmak_NodeGroupTypeScalingGroup_To_v1alpha1_NodeGroupTypeScalingGroup is an autogenerated conversion function.
func Convert_tarmak_NodeGroupTypeScalingGroup_To_v1alpha1_NodeGroupTypeScalingGroup(in *tarmak.NodeGroupTypeScalingGroup, out *NodeGroupTypeScalingGroup, s conversion.Scope) error {
	return autoConvert_tarmak_NodeGroupTypeScalingGroup_To_v1alpha1_NodeGroupTypeScalingGroup(in, out, s)
}
