#cloud-config
repo_update: true
repo_upgrade: all

preserve_hostname: true

write_files:
- path: /etc/systemd/system/ensure-ebs-volume-formatted.service
  permissions: '0644'
  content: |
    [Unit]
    Description=Format EBS volume if needed

    [Service]
    Type=oneshot
    RemainAfterExit=yes
    ExecStart=/bin/bash -c 'blkid /dev/xvdd || (wipefs -fa /dev/xvdd && mkfs.ext4 /dev/xvdd)'

- path: /etc/systemd/system/var-lib-jenkins.mount
  permissions: '0644'
  content: |
    [Unit]
    Description=Mount jenkins data
    After=ensure-ebs-volume-formatted.service
    Requires=ensure-ebs-volume-formatted.service

    [Mount]
    What=/dev/xvdd
    Where=/var/lib/jenkins
    Type=ext4

- path: /etc/systemd/system/jenkins.service.d/10-require-mount.conf
  permissions: '0644'
  content: |
    [Unit]
    After=var-lib-jenkins.mount
    Requires=var-lib-jenkins.mount

    [Service]
    ExecStartPre=/bin/chmod 750 /var/lib/jenkins
    ExecStartPre=/bin/chown jenkins:jenkins /var/lib/jenkins

runcmd:
- hostnamectl set-hostname "jenkins.${dns_zone}"
- curl -sLo /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
- rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
- yum -y update
- yum -y install jenkins
- yum -y install vim docker java git
- usermod -a -G root jenkins
- chcon -vt docker_exec_t /usr/libexec/docker/docker-* /bin/docker* /usr/bin/docker*
- systemctl enable docker.service jenkins.service
- systemctl start docker.service jenkins.service

output : { all : '| tee -a /var/log/cloud-init-output.log' }
