#cloud-config
repo_update: true
repo_upgrade: all

preserve_hostname: true

write_files:
- path: /etc/systemd/system/ensure-ebs-volume-formatted.service
  permissions: '0644'
  content: |
    [Unit]
    Description=Format EBS volume if needed

    [Service]
    Type=oneshot
    RemainAfterExit=yes
    ExecStart=/bin/bash -c 'blkid /dev/xvdd || (wipefs -fa /dev/xvdd && mkfs.ext4 /dev/xvdd)'

- path: /etc/systemd/system/etc-puppetlabs-code.mount
  permissions: '0644'
  content: |
    [Unit]
    Requires=var-lib-puppet.mount
    After=var-lib-puppet.mount

    [Mount]
    What=/var/lib/puppet/code
    Where=/etc/puppetlabs/code
    Type=none
    Options=bind

- path: /etc/systemd/system/etc-puppetlabs-puppet-ssl.mount
  permissions: '0644'
  content: |
    [Unit]
    Requires=var-lib-puppet.mount
    After=var-lib-puppet.mount

    [Mount]
    What=/var/lib/puppet/puppet/ssl
    Where=/etc/puppetlabs/puppet/ssl
    Type=none
    Options=bind

- path: /etc/systemd/system/var-lib-puppet.mount
  permissions: '0644'
  content: |
    [Unit]
    Description=Mount puppet data
    After=ensure-ebs-volume-formatted.service
    Requires=ensure-ebs-volume-formatted.service

    [Mount]
    What=/dev/xvdd
    Where=/var/lib/puppet
    Type=ext4

- path: /etc/systemd/system/puppetserver.service.d/10-require-mounts.conf
  permissions: '0644'
  content: |
    [Unit]
    After=etc-puppetlabs-puppet-ssl.mount etc-puppetlabs-code.mount
    Requires=etc-puppetlabs-puppet-ssl.mount etc-puppetlabs-code.mount

- path: /etc/hosts
  permissions: '0644'
  content: |
    127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
    ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
    127.0.1.1   puppet.${dns_zone}

- path: /etc/puppetlabs/puppet/hiera.yaml
  permissions: '0644'
  content: |
    ---
    :backends:
      - yaml

    :hierarchy:
      - "nodes/%{::trusted.certname}"
      - "role/%{::puppernetes_role}"
      - "environment/%{puppernetes_environment}"
      - common

    :yaml:
      :datadir:

- path: /etc/puppetlabs/puppet/autosign.conf
  permissions: '0644'
  content: |
    *.${region}.compute.internal

- path: /etc/puppetlabs/puppet/fileserver.conf
  permissions: '0644'
  content: |
    [binaries]
    path /var/puppet
      allow *

- path: /var/lib/puppet-deploy/.ssh/authorized_keys
  permissions: '0600'
  content: |
    command="/usr/local/bin/puppet_deploy.sh",no-port-forwarding,no-X11-forwarding,no-pty ${puppet_deploy_key}

- path: /usr/local/bin/puppet_deploy.sh
  permissions: '0755'
  content: |
    #/bin/bash

    set -e
    set -x

    echo "Welcome to puppet deploy"

    dest_dir=/etc/puppetlabs/code/environments
    environment=$SSH_ORIGINAL_COMMAND

    if ! echo -n "$${environment}" | grep -e '^[0-9a-z]\{3,16\}_[0-9a-z]\{3,16\}$'; then
      echo "Sorry environment '$${environment}' is not allowed"
      exit 1
    fi

    rm -rf "$${dest_dir}/.$${environment}-new"
    mkdir -p "$${dest_dir}/.$${environment}-new"
    tar xvzf - -C"$${dest_dir}/.$${environment}-new"
    rm -rf "$${dest_dir}/$${environment}"
    mv "$${dest_dir}/.$${environment}-new" "$${dest_dir}/$${environment}"

    # refresh cache
    echo "Refresh cache of puppetserver"
    test "204" -eq "$(curl -s -o /dev/null -w %{http_code} -k --cert /etc/puppetlabs/puppet/ssl/certs/$(hostname).pem --key /etc/puppetlabs/puppet/ssl/private_keys/$(hostname).pem --cacert /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem -X DELETE https://localhost:8140/puppet-admin-api/v1/environment-cache)"

runcmd:
- systemctl start var-lib-puppet.mount
- mkdir -p /var/lib/puppet/code /var/lib/puppet/puppet/ssl /etc/puppetlabs/code /etc/puppetlabs/puppet/ssl
- systemctl start etc-puppetlabs-code.mount
- systemctl start etc-puppetlabs-puppet-ssl.mount
- useradd -g 0 -u 0 -o -d /var/lib/puppet-deploy puppet-deploy
- rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
- yum -y install epel-release https://yum.theforeman.org/releases/1.13/el7/x86_64/foreman-release.rpm
  yum -y update
- yum -y install foreman-installer
- echo "puppet.${dns_zone}" > /etc/hostname
- hostname -F /etc/hostname
- foreman-installer --foreman-admin-password "${foreman_admin_password}" --foreman-admin-username "${foreman_admin_user}"
- >-
  echo -e "\n:enc_environment: false" >> /etc/foreman/settings.yaml
- systemctl restart httpd

output : { all : '| tee -a /var/log/cloud-init-output.log' }
